const V=window.TRIP_V3;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const start=new Date(V.meta.start);

function tick(){const ms=start-new Date(),d=$('#countdownDays'),h=$('#countdownHours');if(ms<=0){if(d)d.textContent='הטיול התחיל';if(h)h.textContent='';return;}const days=Math.floor(ms/86400000),hours=Math.floor(ms%86400000/3600000),mins=Math.floor(ms%3600000/60000),secs=Math.floor(ms%60000/1000);if(d)d.textContent=`${days} ימים`;if(h)h.textContent=`${String(hours).padStart(2,'0')}:${String(mins).padStart(2,'0')}:${String(secs).padStart(2,'0')}`;}tick();setInterval(tick,1000);
function cleanTitle(day){if(day.id==='prep')return'הכנות';if(day.id==='25.09')return'בנגקוק';if(day.id==='26.09')return'קוסמוי וקופנגן';if(day.id==='27.09')return'קוסמוי';if(day.id==='28.09')return'צ׳יאנג מאי';if(day.id==='29.09'||day.id==='30.09')return'פאי';if(day.id==='01.10'||day.id==='02.10')return'בנגקוק';if(day.id==='03-08.10')return'פתוח לשינויים';if(day.id==='09.10')return'ישראל';return day.title;}
function dayDestination(day){const places={'prep':'לפני הטיסה','25.09':'טיסה לתאילנד','26.09':'קוסמוי וקופנגן','27.09':'קוסמוי','28.09':'צ׳יאנג מאי','29.09':'צ׳יאנג מאי ופאי','30.09':'פאי','01.10':'פאי, צ׳יאנג מאי ובנגקוק','02.10':'בנגקוק','03.10':'בנגקוק','04.10':'קנצ׳נבורי','05.10':'בנגקוק','06.10':'בנגקוק','07.10':'בנגקוק','08.10':'בנגקוק','09.10':'בנגקוק לישראל'};return places[day.id]||cleanTitle(day);}
function dayActivity(day){const activities={'prep':'הכנות וצ׳קליסט','25.09':'טיסת Etihad','26.09':'טיסה, מעבורת ופול מון','27.09':'מעבורת ומלון','28.09':'טיסה ומלון','29.09':'פילים והמשך לפאי','30.09':'זיפליין וערב בפאי','01.10':'נסיעה וטיסה','02.10':'מקדשים והנהר','03.10':'שווקים / יציאה לקו טאו','04.10':'מפלים / צלילות קו טאו','05.10':'פארקים / צלילות קו טאו','06.10':'שופינג / צלילה אחרונה','07.10':'גיבוי / חזרה לבנגקוק','08.10':'השלמות ואריזה','09.10':'טיסת חזרה'};return activities[day.id]||day.title;}
function dayDuration(day){const durations={'prep':'עד הטיסה: 7 ימים','25.09':'סה״כ: כ־12 שעות','26.09':'סה״כ: יום ו־1 שעה','27.09':'סה״כ: כ־16 שעות','28.09':'סה״כ: יום ו־6 שעות','29.09':'סה״כ: יום ו־12 שעות','30.09':'סה״כ: יום אחד','01.10':'סה״כ: 2 ימים בבנגקוק','02.10':'סה״כ: יום אחד','03.10':'סה״כ: יום אחד','04.10':'סה״כ: יום אחד','05.10':'סה״כ: יום אחד','06.10':'סה״כ: יום אחד','07.10':'סה״כ: יום אחד','08.10':'סה״כ: יום אחד','09.10':'סה״כ: כ־12 שעות'};return durations[day.id]||'סה״כ: יום אחד';}
function dayIcon(day){return `<img src="${esc(day.icon)}" alt="" loading="lazy">`;}
function nextDay(day){const i=V.days.findIndex(x=>x.id===day.id);return i>=0&&i<V.days.length-1?V.days[i+1]:null;}
function renderDays(){const g=$('#journeyGrid');g.innerHTML=V.days.map(day=>`<button class="day-tile" data-day="${esc(day.id)}" type="button"><span class="tiny-icon">${dayIcon(day)}</span><span class="tile-date">${esc(day.date)}</span><b class="tile-place">${esc(dayDestination(day))}</b><strong>${esc(dayActivity(day))}</strong><small class="tile-duration">${esc(dayDuration(day))}</small><em class="tile-status${day.planFlexible?' flexible':''}">${day.planFlexible?'נתון לשינוי':'&nbsp;'}</em></button>`).join('')+`<button id="generalLinksCard" class="day-tile general-tile" type="button"><span class="tiny-icon">☰</span><span class="tile-date">כללי</span><strong>קישורים שימושיים</strong><em class="tile-status">&nbsp;</em></button>`;$$('.day-tile[data-day]').forEach(b=>b.onclick=()=>openDay(b.dataset.day));$('#generalLinksCard').onclick=openGeneral;}
function linkButtons(items=[]){return items.length?`<div class="action-stack">${items.map(([t,u])=>`<a href="${esc(u)}" target="_blank" rel="noopener">${esc(t)}</a>`).join('')}</div>`:'';}
function transportType(mode=''){const m=mode.toLowerCase();if(m.includes('air')||m.includes('etihad')||m.includes('pg'))return'✈️ טיסה';if(m.includes('ferry')||m.includes('queen')||m.includes('boat'))return'🚤 מעבורת / ספידבוט';if(m.includes('prem pracha')||m.includes('van')||m.includes('minivan')||m.includes('מיניוואן'))return'🚐 ואן / מיניוואן';if(m.includes('איסוף')||m.includes('elephant'))return'🚐 הסעה מאורגנת';if(m.includes('taxi')||m.includes('grab')||m.includes('מונית'))return'🚕 מונית / Grab';return'🚐 תחבורה';}
function isFlight(s){const m=(s?.mode||'').toLowerCase();return m.includes('air')||m.includes('etihad')||/pg\d+/i.test(s?.mode||'');}
function flightBoard(s){if(!isFlight(s))return'';const f=s.from||'';let u='',l='';if(f.includes('תל אביב')){u='https://www.iaa.gov.il/en/';l='לוח הטיסות נתב״ג';}else if(f.includes('אבו דאבי')){u='https://www.zayedinternationalairport.ae/en/flights-and-check-in/flight-status/departures';l='לוח הטיסות אבו דאבי';}else if(f.includes('בנגקוק')){u='https://suvarnabhumi.airportthai.co.th/flight?type=departure';l='לוח הטיסות סוברנבומי';}else if(f.includes('צ׳יאנג מאי')||f.includes("צ'יאנג מאי")){u='https://chiangmai.airportthai.co.th/flight?type=departure';l='לוח הטיסות צ׳יאנג מאי';}else if(f.includes('קוסמוי')){u='https://www.bangkokair.com/';l='Bangkok Airways - בדיקת טיסה';}return u?`<a href="${u}" target="_blank" rel="noopener">🛫 ${l}</a>`:'';}
function movementCard(s,idx){const board=flightBoard(s);return `<article class="move-card"><div class="move-kicker">${idx+1}. ${transportType(s.mode)}</div><div class="move-title"><strong>מ- ${esc(s.from)}</strong><span>אל</span><strong>${esc(s.to)}</strong></div><div class="times"><div><small>יציאה, שעון מקומי</small><b>${esc(s.depart)}</b></div><div><small>הגעה, שעון מקומי</small><b>${esc(s.arrive)}</b>${s.duration?`<em>${esc(s.duration)}</em>`:''}</div></div><p><b>אמצעי:</b> ${esc(s.mode)}</p><p><b>🧳 מזוודה:</b> ${esc(s.luggage)}</p>${s.verify?`<p class="verify">🟠 ${esc(s.verify)}</p>`:''}<div class="action-stack">${board}${(s.nav||[]).map(([t,u])=>`<a href="${esc(u)}" target="_blank" rel="noopener">📍 ${esc(t)}</a>`).join('')}</div></article>`;}
function docPurpose(title=''){const t=title.toLowerCase();if(t.includes('etihad')||t.includes('bangkok air'))return'כרטיס טיסה';if(t.includes('מעבור')||t.includes('queen')||t.includes('ferry')||t.includes('speedboat'))return'כרטיס למעבורת';if(t.includes('prem pracha')||t.includes('van')||t.includes('מיניוואן'))return'כרטיס לוואן';if(t.includes('elephant')||t.includes('zipline')||t.includes('פיל')||t.includes('אומגה'))return'כרטיס / אישור לאטרקציה';if(t.includes('hotel')||t.includes('מלון')||t.includes('paradise')||t.includes('rawee')||t.includes('reverie')||t.includes('pullman'))return'שובר מלון';if(t.includes('דרכון'))return'דרכון';if(t.includes('חיסונים'))return'תיעוד חיסונים';if(t.includes('passport'))return'מסמך ביטוח';return'מסמך רלוונטי';}
function docsCard(day){const docs=day.docs||[];return `<section class="info-card"><h3>🎫 מסמכים רלוונטיים</h3>${docs.length?`<div class="ordered-docs">${docs.map(([t,u],i)=>`<a href="${esc(u)}" target="_blank" rel="noopener"><span>${i+1}</span><div><b>${esc(docPurpose(t))}</b><small>${esc(t)}</small></div></a>`).join('')}</div>`:'<p>אין כרגע מסמך ייעודי ליום הזה.</p>'}${day.folder?`<a class="folder-link" href="${esc(day.folder)}" target="_blank" rel="noopener">📂 תיקיית היום</a>`:''}</section>`;}
function chabadCard(c){if(!c)return'';const a=[['📍 נווט לבית חב״ד',c.maps],['🌐 אתר בית חב״ד',c.site]];if(c.phone)a.push(['📞 התקשר',c.phone]);return `<section class="info-card"><h3>✡️ בית חב״ד קרוב</h3><strong>${esc(c.name)}</strong>${linkButtons(a)}</section>`;}
function flexCard(day){return `<section class="info-card"><h3>🕊️ זמן חופשי לשינויים</h3><p>${esc(day.flex||'להשאיר זמן חופשי להחלטה במקום.')}</p></section>`;}
function clothingCard(day){if(!day.clothing)return'';const c=day.clothing;return `<section class="info-card"><h3>👕 לבוש מומלץ</h3><p><b>ביום:</b> ${esc(c.day)}</p><p><b>לקחת בתיק:</b> ${esc(c.bag)}</p>${c.note?`<p class="verify">${esc(c.note)}</p>`:''}</section>`;}
function optionalRoutesCard(day){const routes=day.optionalRoutes||[];if(!routes.length)return'';const flexible=!!day.planFlexible;return `<section class="info-card"><h3>${flexible?'🟡 נתון לשינוי, לא הוזמן':'🧭 מסלולים אופציונליים'}</h3><p class="option-note">${flexible?'זהו שיבוץ מוצע בלבד. לא נקנה כרטיס ולא נוצר אילוץ. אפשר להחליף יום או מסלול.':'לא חייבים לבחור עכשיו. פותחים מסלול לפי מזג האוויר והכוח.'}</p><div class="option-list">${routes.map(r=>`<article class="option-card"><div class="option-head"><span>${esc(r.icon||'📍')}</span><div><b>${esc(r.title)}</b><small>${esc(r.when||'')}</small></div></div><p>${esc(r.note||'')}</p><ol>${(r.stops||[]).map(s=>`<li>${esc(s)}</li>`).join('')}</ol>${linkButtons(r.links||[])}</article>`).join('')}</div></section>`;}
function foodCard(day){const places=day.food||[];if(!places.length)return'';return `<section class="info-card"><h3>🐟 אוכל בטוח ומתאים</h3><p class="option-note">עדיפות למסעדות מסודרות ולקניונים. דגים נאים רק במקום עם קירור ותחלופה גבוהים.</p><div class="food-list">${places.map(x=>`<article class="food-card"><b>${esc(x.name)}</b><small>${esc(x.area||'')}</small><p>${esc(x.fit||'')}</p>${linkButtons([['📍 ניווט',x.maps]])}</article>`).join('')}</div></section>`;}
function attractionBriefsCard(day){const items=day.attractionBriefs||[];if(!items.length)return'';return `<section class="info-card"><h3>🎟️ מידע לפני שמחליטים</h3><p class="option-note">מחירים ושעות עשויים להשתנות. לפני יציאה פותחים את המקור המצורף ובודקים שאין סגירה מיוחדת.</p><div class="attraction-briefs">${items.map(x=>`<article class="attraction-brief${x.paid?' paid':''}"><div class="attraction-brief-head"><b>${esc(x.name)}</b><span>${x.paid?'בתשלום':'ללא כרטיס כניסה'}</span></div><p><strong>עלות:</strong> ${esc(x.cost)}</p><p><strong>שעות:</strong> ${esc(x.hours)}</p><p><strong>הזמנה:</strong> ${esc(x.booking)}</p>${x.note?`<p class="attraction-note">${esc(x.note)}</p>`:''}${x.about?`<details class="attraction-about"><summary>מידע מפורט</summary><p>${esc(x.about)}</p></details>`:''}${linkButtons(x.links||[])}</article>`).join('')}</div></section>`;}
function transportCard(){const items=[
 {icon:'🚕',name:'Grab',status:'להוריד ולהגדיר אשראי',note:'האפליקציה הראשית שלך למוניות, לנסיעות עירוניות ולשדות תעופה.',url:'https://play.google.com/store/apps/details?id=com.grabtaxi.passenger'},
 {icon:'🚕',name:'Bolt',status:'להוריד כגיבוי',note:'שימושי להשוואת מחיר וזמינות מול Grab. כדאי להגדיר אמצעי תשלום מראש.',url:'https://play.google.com/store/apps/details?id=ee.mtakso.client'},
 {icon:'🗺️',name:'Google Maps',status:'חובה לניווט',note:'מסלולים ברגל, ברכבות ובתחבורה ציבורית. אם כבר מותקן, אין צורך לעשות דבר.',url:'https://play.google.com/store/apps/details?id=com.google.android.apps.maps'},
 {icon:'🚆',name:'BTS Skytrain',status:'אתר בלבד',note:'אין צורך באפליקציה נפרדת. Google Maps והאתר הרשמי מספיקים לבדיקת תחנות ותעריפים.',url:'https://www.bts.co.th/eng/'},
 {icon:'🚇',name:'Bangkok MRT',status:'אתר בלבד',note:'אין צורך באפליקציה נפרדת. משתמשים ב-Google Maps ובאתר הרשמי.',url:'https://metro.bemplc.co.th/'},
 {icon:'🚌',name:'ViaBus',status:'אופציונלי',note:'להוריד רק אם תבחר לנסוע הרבה באוטובוסים בבנגקוק. למסלול הנוכחי הוא לא הכרחי.',url:'https://play.google.com/store/apps/details?id=com.indyzalab.transitia'},
 {icon:'🚐',name:'12Go',status:'אתר בלבד',note:'להזמנת ואנים, רכבות ומעבורות בין יעדים. אין צורך באפליקציה למסלול שכבר הוזמן.',url:'https://12go.asia/'}
];return `<section class="info-card"><h3>🚕 תחבורה ואפליקציות</h3><p class="option-note"><b>להכין לפני הטיסה:</b> Grab ו-Bolt עם מספר טלפון ואמצעי תשלום. Google Maps לניווט. שאר השירותים נפתחים רק כשצריך.</p><div class="transport-list">${items.map(x=>`<a href="${esc(x.url)}" target="_blank" rel="noopener"><span>${x.icon}</span><div><b>${esc(x.name)}</b><em class="transport-status">${esc(x.status)}</em><small>${esc(x.note)}</small></div></a>`).join('')}</div></section>`;}
const PREP_ITEMS_KEY='thailand-trip-prep-items-v2';
const PACKING_ITEMS=[
 ['👕','חולצות קצרות','8','יומיום, טיסות, איים והחלפות'],
 ['👔','חולצות למקדשים / ערב','2','כתפיים מכוסות ולבוש מכבד'],
 ['🩳','מכנסיים קצרים','4','איים, פול מון, פילים ויומיום'],
 ['👖','מכנסיים ארוכים קלים','2','טיסות, מקדשים וערב'],
 ['🩲','תחתונים','9','שבוע, החלפות ורזרבה'],
 ['🧦','זוגות גרביים','7','טיסות, הליכה ופילים'],
 ['🩱','בגדי ים','2','אחד בשימוש ואחד מתייבש'],
 ['😴','סט שינה','1','סט אחד'],
 ['🧥','עליונית דקה','1','טיסות ומזגן'],
 ['🌧️','מעיל גשם מתקפל','1','לגשם'],
 ['👟','נעלי ספורט','1 זוג','הליכה, פילים וטיסות'],
 ['🩴','כפכפים','1 זוג','איים, מלון ובריכה'],
 ['🧢','כובע','1','טיולי יום'],
 ['🧺','שק לבגדים מלוכלכים','1','למעברים בין מלונות']
];
function packingCard(){
 return `<section class="info-card packing-card"><h3>🧳 רשימת מזוודה</h3><p class="option-note">הכמויות מחושבות לפי הסטים והפעילויות במסלול, עם כביסה במהלך הטיול.</p><div class="packing-visual">${PACKING_ITEMS.map(x=>`<div class="packing-item"><span>${x[0]}</span><div><b>${esc(x[1])}</b><strong>${esc(x[2])}</strong><small>${esc(x[3])}</small></div></div>`).join('')}</div><details class="attraction-about"><summary>פירוט הסטים לפי פעילות</summary><p><b>טיסה:</b> חולצה קצרה + מכנס ארוך + תחתונים + גרביים. <b>Full Moon:</b> חולצה קצרה + מכנס קצר. <b>איים:</b> חולצה קצרה + מכנס קצר + בגד ים. <b>פילים:</b> חולצה שאפשר ללכלך + מכנס קצר/טיולים + גרביים + נעליים סגורות. <b>מקדשים:</b> חולצה שמכסה כתפיים + מכנס ארוך. <b>בנגקוק:</b> קצר ליומיום, עם סט מכבד כגיבוי. <b>טיסה חזרה:</b> לשמור חולצה, תחתונים וגרביים נקיים בצד.</p></details></section>`;
}
function loadPrepItems(){
 const saved=localStorage.getItem(PREP_ITEMS_KEY);if(saved){try{const items=JSON.parse(saved)||[];if(!localStorage.getItem('prep-integrated-v1')){const oldDone=JSON.parse(localStorage.getItem('travel_fixed_done')||'{}'),added=['מטען נייד','שני מטענים','לקנות SIM מקומי בתאילנד - לבדוק 7-Eleven או דוכן מפעיל בנמל התעופה סוברנבומי (Suvarnabhumi Airport)'];added.forEach((title,index)=>{if(!items.some(item=>item.title===title))items.push({id:'prep-integrated-'+index,title,done:!!oldDone[index]})});localStorage.setItem('prep-integrated-v1','1');localStorage.setItem(PREP_ITEMS_KEY,JSON.stringify(items))}return items}catch(_){}}
 const base=['לקחת מטען ומתאם לשקע','לקנות דוחה יתושים בסופר בתאילנד','דרכון בתוקף','5 צילומי דרכון מודפסים','עותק דיגיטלי של הדרכון בטלפון ובענן','PassportCard והכרטיס הפיזי','TDAC בתוך 3 ימים לפני ההגעה','בדיקת כרטיס אשראי נוסף','בדיקת מזוודה וטרקר Google Find Hub','רישיון נהיגה בינלאומי','בדיקת eSIM / SIM','מטרייה קטנה ומתקפלת מהארץ','בדיקת רחפן, סוללות, כרטיס זיכרון ואישורים'];
 const extra=JSON.parse(localStorage.getItem('prep_extra')||'[]'),done=JSON.parse(localStorage.getItem('prep_done')||'{}');
 const integrated=['מטען נייד','שני מטענים','לקנות SIM מקומי בתאילנד - לבדוק 7-Eleven או דוכן מפעיל בנמל התעופה סוברנבומי (Suvarnabhumi Airport)'],oldDone=JSON.parse(localStorage.getItem('travel_fixed_done')||'{}');
 const items=[...base,...extra].map((title,index)=>({id:'prep-'+Date.now()+'-'+index,title,done:!!done[index]}));integrated.forEach((title,index)=>items.push({id:'prep-integrated-'+index,title,done:!!oldDone[index]}));localStorage.setItem('prep-integrated-v1','1');localStorage.setItem(PREP_ITEMS_KEY,JSON.stringify(items));return items;
}
function savePrepItems(items){localStorage.setItem(PREP_ITEMS_KEY,JSON.stringify(items))}
function prepList(){return loadPrepItems().map(item=>`<div class="prep-row"><label><input type="checkbox" data-prep-id="${esc(item.id)}" ${item.done?'checked':''}><span>${esc(item.title)}</span></label><div class="prep-actions"><button class="edit-prep" data-prep-id="${esc(item.id)}" type="button">עריכה</button><button class="remove-prep" data-prep-id="${esc(item.id)}" type="button">מחק</button></div></div>`).join('');}
function bindInline(){const c=$('#closeInline');if(c)c.onclick=()=>{$('#inlinePanel').classList.remove('show');$('#inlinePanel').innerHTML='';};$$('#inlinePanel [data-prep-id][type="checkbox"]').forEach(x=>x.onchange=()=>{const items=loadPrepItems(),item=items.find(v=>v.id===x.dataset.prepId);if(item)item.done=x.checked;savePrepItems(items);});$$('#inlinePanel .edit-prep').forEach(b=>b.onclick=e=>{e.preventDefault();const items=loadPrepItems(),item=items.find(v=>v.id===b.dataset.prepId);if(!item)return;const title=prompt('עריכת הכנה',item.title);if(title===null||!title.trim())return;item.title=title.trim();savePrepItems(items);openDay('prep');});$$('#inlinePanel .remove-prep').forEach(b=>b.onclick=e=>{e.preventDefault();const items=loadPrepItems(),item=items.find(v=>v.id===b.dataset.prepId);if(!item||!confirm('למחוק את ההכנה „'+item.title+'”?'))return;savePrepItems(items.filter(v=>v.id!==item.id));openDay('prep');});const add=$('#addPrepBtn');if(add)add.onclick=()=>{const title=prompt('מה להוסיף להכנות?');if(!title?.trim())return;const items=loadPrepItems();items.push({id:'prep-'+Date.now(),title:title.trim(),done:false});savePrepItems(items);openDay('prep');};}
function openDay(id){const day=V.days.find(x=>x.id===id);if(!day)return;const n=nextDay(day),p=$('#inlinePanel');let html=`<div class="inline-head"><div><small>${esc(day.date)}</small><h2>${esc(cleanTitle(day))}</h2><p>⏱️ ${esc(day.stay)}${n?` · היעד הבא: ${esc(cleanTitle(n))}`:''}</p><small class="time-zone-note">🕒 פורמט 24 שעות. כל שעה היא לפי הזמן המקומי במקום האירוע, ולא שעון ישראל, אלא אם האירוע בישראל.</small></div><button id="closeInline" class="close-red" type="button">סגור</button></div>`;if(id==='prep')html+=`<section class="info-card"><div class="section-title-row"><h3>✅ הכנות לטיול</h3><button id="addPrepBtn" class="add-btn" type="button">+ הוספה</button></div>${prepList()}</section>${packingCard()}`;if(day.segments?.length)html+=`<section class="info-card"><h3>🚦 המסלול של היום</h3>${day.segments.map(movementCard).join('')}</section>`;html+=clothingCard(day)+optionalRoutesCard(day)+attractionBriefsCard(day)+foodCard(day)+docsCard(day);if(day.links?.length)html+=`<section class="info-card"><h3>🔗 קישורים ויצירת קשר</h3>${linkButtons(day.links)}</section>`;html+=chabadCard(day)+flexCard(day);p.innerHTML=html;p.classList.add('show');bindInline();setTimeout(()=>p.scrollIntoView({behavior:'smooth',block:'start'}),30);}
function openGeneral(){const p=$('#inlinePanel');p.innerHTML=`<div class="inline-head"><div><small>כללי</small><h2>קישורים ודברים חשובים</h2></div><button id="closeInline" class="close-red" type="button">סגור</button></div><section class="info-card"><h3>פעולות מהירות</h3><div class="important-actions"><button type="button" onclick="openSOS()"><span>🆘</span><b>מוקדי חירום</b><small>משטרה, כיבוי ורפואה</small></button><button type="button" onclick="openSavedPlaces()"><span>📍</span><b>שמירת מקום</b><small>שמור את המיקום הנוכחי</small></button><a href="https://chatgpt.com/g/g-p-6a9facc60a388191b9b862074bbf96b6-tysh-ltylnd/c/6aaa3daf-137c-83eb-9aa6-7cc70b214966" target="_blank" rel="noopener"><span>💬</span><b>השיחה שלנו</b><small>המשך תכנון ב-ChatGPT</small></a></div></section>${transportCard()}<section class="info-card"><h3>קישורים שימושיים</h3>${linkButtons([['🇹🇭 רשות התיירות הרשמית Amazing Thailand','https://thai.tourismthailand.org/Home'],['🧳 Google Find Hub','https://www.google.com/android/find/'],['🚁 CAAT UAS Portal','https://uasportal.caat.or.th/'],['🇮🇱 מדריך רחפן Travel Gal','https://www.travelgal.co.il/post/dronethailand'],['🛂 TDAC הרשמי','https://tdac.immigration.go.th'],['🧺 מכבסה קרוב אליי','https://www.google.com/maps/search/?api=1&query=laundry'],['✡️ בתי חב״ד בתאילנד','https://chabadthailand.co.il/']])}</section>`;p.classList.add('show');bindInline();p.scrollIntoView({behavior:'smooth',block:'start'});}

const mapStops=[['✈️','נמל התעופה בן גוריון (Ben Gurion Airport)',32.0114,34.8867],['✈️','נמל התעופה אבו דאבי (Zayed International Airport)',24.4330,54.6511],['✈️','נמל התעופה סוברנבומי (Suvarnabhumi Airport)',13.6900,100.7501],['✈️','נמל התעופה קוסמוי (Samui Airport)',9.5478,100.0623],['🚤','נקודת Haad Rin Queen בקוסמוי',9.5584,100.0560],['🚤','רציף האד רין (Haad Rin Pier)',9.6760,100.0660],['🏨','ליטל פרדייז (Little Paradise)',9.6750,100.0675],['🎉','פול מון פארטי, האד רין נוק (Full Moon Party, Haad Rin Nok)',9.6759,100.0708],['🚤','רציף האד רין (Haad Rin Pier)',9.6760,100.0660],['🏨','סאמוי פיר ביץ׳ פרונט ריזורט (Samui Pier Beach Front Resort)',9.5584,100.0560],['✈️','נמל התעופה קוסמוי (Samui Airport)',9.5478,100.0623],['✈️','נמל התעופה צ׳יאנג מאי (Chiang Mai International Airport)',18.7668,98.9626],['🏨','ארון ראווי (Arun Rawee)',18.7900,98.9895],['🐘','אלפנט נייצ׳ר פארק (Elephant Nature Park)',19.2156,98.8597],['🚐','צ׳יאנג מאי ארקייד 2 (Chiang Mai Arcade 2)',18.8007,99.0175],['🚐','תחנת פאי (Pai Bus Station)',19.3580,98.4407],['🏨','רברי סיאם ריזורט (Reverie Siam Resort)',19.3511,98.4361],['🌳','פאי זיפליין (Pai Zipline)',19.3300,98.4300],['🚐','תחנת פאי (Pai Bus Station)',19.3580,98.4407],['🚐','צ׳יאנג מאי ארקייד 2 (Chiang Mai Arcade 2)',18.8007,99.0175],['✈️','נמל התעופה צ׳יאנג מאי (Chiang Mai International Airport)',18.7668,98.9626],['✈️','נמל התעופה סוברנבומי (Suvarnabhumi Airport)',13.6900,100.7501],['🏨','פולמן בנגקוק הוטל ג׳י (Pullman Bangkok Hotel G)',13.7257,100.5258],['✈️','נמל התעופה סוברנבומי (Suvarnabhumi Airport)',13.6900,100.7501],['✈️','נמל התעופה אבו דאבי (Zayed International Airport)',24.4330,54.6511],['✈️','נמל התעופה בן גוריון (Ben Gurion Airport)',32.0114,34.8867]];
let mapInstance=null,mapMarkers=[];
function markerIcon(n,emoji){return L.divIcon({className:'trip-marker-wrap',html:`<div class="trip-marker"><b>${n}</b><span>${emoji}</span></div>`,iconSize:[38,38],iconAnchor:[19,34],popupAnchor:[0,-34]});}
function mapsUrl(name){return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(name)}`;}
function openMap(){const wrap=$('#mapSection');wrap.classList.add('show');wrap.scrollIntoView({behavior:'smooth',block:'start'});if(mapInstance){setTimeout(()=>mapInstance.invalidateSize(),200);return;}mapInstance=L.map('tripMap',{zoomControl:true}).setView([13.3,100.5],5);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(mapInstance);mapMarkers=[];const route=[],seen={};mapStops.forEach((p,i)=>{const [emoji,name,lat,lon]=p,key=`${lat},${lon}`;seen[key]=(seen[key]||0)+1;const k=seen[key]-1,display=[lat+(k?0.003*k:0),lon+(k?0.003*k:0)];route.push([lat,lon]);const next=mapStops[i+1];const routeLink=next?`<a href="https://www.google.com/maps/dir/?api=1&origin=${lat},${lon}&destination=${next[2]},${next[3]}" target="_blank" rel="noopener">🧭 מסלול אל נקודה ${i+2}</a>`:'';const marker=L.marker(display,{icon:markerIcon(i+1,emoji)}).addTo(mapInstance).bindPopup(`<div class="map-popup"><strong>${i+1}. ${esc(name)}</strong><a href="${mapsUrl(name)}" target="_blank" rel="noopener">📍 נווט לנקודה</a>${routeLink}</div>`);mapMarkers.push(marker);});L.polyline(route,{weight:4,opacity:.6,dashArray:'8 8'}).addTo(mapInstance);mapInstance.fitBounds(route,{padding:[30,30]});renderMapLegend();$('#mapStatus').textContent=`${mapStops.length} נקודות במסלול לפי הסדר.`;}
function focusMapPoint(i){const m=mapMarkers[i];if(!m)return;mapInstance.setView(m.getLatLng(),14,{animate:true});m.openPopup();$('#tripMap').scrollIntoView({behavior:'smooth',block:'center'});}
function renderMapLegend(){$('#mapLegend').innerHTML=mapStops.map(([emoji,name],i)=>`<button type="button" class="map-legend-row" data-map-index="${i}"><span>${i+1}</span><b>${emoji} ${esc(name)}</b><em>הצג במפה</em></button>`).join('');$$('#mapLegend button').forEach(b=>b.onclick=()=>focusMapPoint(+b.dataset.mapIndex));}
$('#mapBanner').onclick=openMap;$('#mapTool').onclick=openMap;$('#closeMap').onclick=()=>$('#mapSection').classList.remove('show');$('#chabadTool').onclick=()=>window.open('https://chabadthailand.co.il/','_blank','noopener');$('#docsTool').onclick=()=>{const p=$('#inlinePanel'),days=V.days.filter(d=>d.docs?.length);p.innerHTML=`<div class="inline-head"><div><small>מסמכים</small><h2>מסמכים לפי יום</h2></div><button id="closeInline" class="close-red" type="button">סגור</button></div>${days.map(d=>`<div class="docs-day-group"><h3 class="docs-day-heading">${esc(d.date)} · ${esc(cleanTitle(d))}</h3>${docsCard(d)}</div>`).join('')}`;p.classList.add('show');bindInline();p.scrollIntoView({behavior:'smooth',block:'start'});};
renderDays();
