const V=window.TRIP_V3;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const start=new Date(V.meta.start);

function tick(){
  const ms=start-new Date();
  const dEl=$('#countdownDays'),hEl=$('#countdownHours');
  if(ms<=0){if(dEl)dEl.textContent='הטיול התחיל';if(hEl)hEl.textContent='';return;}
  const days=Math.floor(ms/86400000), totalHours=Math.floor(ms/3600000), mins=Math.floor(ms%3600000/60000), secs=Math.floor(ms%60000/1000);
  if(dEl)dEl.textContent=`${days} ימים`;
  if(hEl)hEl.textContent=`${totalHours} שעות · ${String(mins).padStart(2,'0')} דקות · ${String(secs).padStart(2,'0')} שניות`;
}
tick();setInterval(tick,1000);

function currentDayId(){const n=new Date(),y=n.getFullYear(),m=String(n.getMonth()+1).padStart(2,'0'),d=String(n.getDate()).padStart(2,'0');if(n<start)return'prep';if(y===2026&&m==='09'&&+d>=25&&+d<=30)return`${d}.${m}`;if(y===2026&&m==='10'&&+d===1)return'01.10';if(y===2026&&m==='10'&&+d===2)return'02.10';if(y===2026&&m==='10'&&+d>=3&&+d<=8)return'03-08.10';if(y===2026&&m==='10'&&+d===9)return'09.10';return'prep'}
function displayTitle(day){if(day.id==='27.09')return'קוסמוי';if(day.id==='29.09')return'פאי';return day.title;}
function dayIcon(day){return `<img src="${esc(day.icon)}" alt="" loading="lazy">`}
function docGlyph(title=''){const t=title.toLowerCase();if(t.includes('etihad')||t.includes('bangkok air')||t.includes('טיסה'))return'✈️';if(t.includes('מעבור')||t.includes('queen')||t.includes('ferry'))return'🚤';if(t.includes('hotel')||t.includes('מלון')||t.includes('paradise')||t.includes('rawee')||t.includes('reverie')||t.includes('pullman'))return'🏨';if(t.includes('elephant')||t.includes('פיל'))return'🐘';if(t.includes('passport'))return'🛡️';return'📄'}
function isFlight(s){const m=(s?.mode||'').toLowerCase();return m.includes('air')||m.includes('etihad')||/pg\d+/i.test(s?.mode||'')}
function cardTransport(day){const segs=day.segments||[];if(!segs.length)return'';const s=segs[0];if(isFlight(s))return `<span class="transport-line">✈️ ${esc(s.mode)}<small>גייט/טרמינל: יתעדכן בלוח הטיסות ביום הטיסה</small></span>`;const m=(s.mode||'').toLowerCase();if(m.includes('ferry')||m.includes('queen')||m.includes('boat'))return `<span class="transport-line">🚤 ${esc(s.mode)}<small>רציף: לפי הכרטיס והאימות התפעולי</small></span>`;if(m.includes('prem pracha')||m.includes('van')||m.includes('מיניוואן'))return `<span class="transport-line">🚐 ${esc(s.mode)}</span>`;if(m.includes('elephant')||m.includes('איסוף'))return `<span class="transport-line">🚐 הסעה לפעילות</span>`;return `<span class="transport-line">🚐 ${esc(s.mode)}</span>`}
function miniDocs(day){const docs=day.docs||[];if(!docs.length)return'<span class="no-doc">אין מסמך</span>';return docs.map(([t,u],i)=>`<a href="${esc(u)}" target="_blank" rel="noopener"><span class="mini-num">${i+1}</span><span>${docGlyph(t)}</span><em>${esc(t)}</em></a>`).join('')}
function renderDays(){
 const grid=$('#journeyGrid');
 grid.innerHTML=V.days.map(day=>`<article class="journey-card ${day.id===currentDayId()?'today-card':''}" data-day="${esc(day.id)}"><button class="day-main" type="button">${dayIcon(day)}<span>${esc(day.date)}</span><strong>${esc(displayTitle(day))}</strong>${cardTransport(day)}<small>⏱️ ${esc(day.stay)}</small></button><div class="mini-docs">${miniDocs(day)}</div></article>`).join('')+`<article class="journey-card general-card"><button id="generalLinksCard" class="day-main" type="button"><span class="general-icon">☰</span><span>כללי</span><strong>קישורים שימושיים</strong><span class="transport-line">🧳 מזוודה · 🚁 רחפן · כניסה · ביטוח</span><small>כל מה שלא שייך ליום מסוים</small></button></article>`;
 $$('.journey-card[data-day] .day-main').forEach(b=>b.onclick=()=>openDay(b.closest('.journey-card').dataset.day));
 $('#generalLinksCard').onclick=openGeneral;
}
function linkButtons(items=[]){return items.length?`<div class="action-grid">${items.map(([t,u])=>`<a href="${esc(u)}" target="_blank" rel="noopener">${esc(t)}</a>`).join('')}</div>`:''}
function transportType(mode=''){const m=mode.toLowerCase();if(m.includes('air')||m.includes('etihad')||m.includes('pg'))return'✈️ טיסה';if(m.includes('ferry')||m.includes('queen')||m.includes('boat'))return'🚤 מעבורת / ספידבוט';if(m.includes('prem pracha')||m.includes('van')||m.includes('minivan')||m.includes('מיניוואן'))return'🚐 ואן / מיניוואן';if(m.includes('pickup')||m.includes('איסוף')||m.includes('elephant'))return'🚐 הסעה מאורגנת';if(m.includes('taxi')||m.includes('grab')||m.includes('מונית'))return'🚕 מונית / Grab';return'🚐 תחבורה'}
function flightBoard(s){if(!isFlight(s))return'';const from=s.from||'';let url='',label='';if(from.includes('תל אביב')){url='https://www.iaa.gov.il/en/';label='לוח הטיסות נתב״ג';}else if(from.includes('אבו דאבי')){url='https://www.zayedinternationalairport.ae/en/flights-and-check-in/flight-status/departures';label='לוח הטיסות אבו דאבי';}else if(from.includes('בנגקוק')){url='https://suvarnabhumi.airportthai.co.th/flight?type=departure';label='לוח הטיסות סוברנבומי';}else if(from.includes('צ׳יאנג מאי')||from.includes("צ'יאנג מאי")){url='https://chiangmai.airportthai.co.th/flight?type=departure';label='לוח הטיסות צ׳יאנג מאי';}else if(from.includes('קוסמוי')){url='https://www.bangkokair.com/';label='Bangkok Airways - בדיקת טיסה';}return url?`<a href="${url}" target="_blank" rel="noopener">🛫 ${label}</a>`:''}
function movementCard(s,idx){const board=flightBoard(s);return `<article class="move-card"><div class="move-kicker">קטע ${idx+1} · ${transportType(s.mode)}</div><div class="move-title"><strong>מ- ${esc(s.from)}</strong><span class="to-word">אל</span><strong>${esc(s.to)}</strong></div><div class="times"><div><small>יציאה</small><b>${esc(s.depart)}</b></div><div><small>הגעה</small><b>${esc(s.arrive)}${s.duration?` <span class="duration">(${esc(s.duration)})</span>`:''}</b></div></div><div class="move-meta"><p><b>אמצעי:</b> ${esc(s.mode)}</p><p><b>🧳 מזוודה:</b> ${esc(s.luggage)}</p>${s.verify?`<p class="verify">🟠 <b>דורש אימות מידע או נתונים:</b> ${esc(s.verify)}</p>`:''}</div><div class="action-grid">${board}${(s.nav||[]).map(([t,u])=>`<a href="${esc(u)}" target="_blank" rel="noopener">📍 ${esc(t)}</a>`).join('')}</div></article>`}
function chabadCard(c){if(!c)return'';const arr=[['📍 נווט לבית חב״ד',c.maps],['🌐 אתר בית חב״ד',c.site]];if(c.phone)arr.push(['📞 התקשר',c.phone]);return `<section class="info-card"><h3>✡️ בית חב״ד קרוב</h3><strong>${esc(c.name)}</strong>${linkButtons(arr)}</section>`}
function docsCard(day){const docs=day.docs||[];return `<section class="info-card"><h3>🎫 מסמכים רלוונטים</h3>${docs.length?`<div class="ordered-docs">${docs.map(([t,u],i)=>`<a href="${esc(u)}" target="_blank" rel="noopener"><span>${i+1}</span><b>${docGlyph(t)} ${esc(t)}</b></a>`).join('')}</div>`:'<p>אין כרגע מסמך ייעודי ליום הזה.</p>'}${day.folder?linkButtons([['📂 תיקיית היום',day.folder]]):''}</section>`}
function flexCard(day){return `<section class="info-card flex-card"><h3>🕊️ זמן חופשי לשינויים</h3><p>${esc(day.flex||'להשאיר זמן חופשי להחלטה במקום.')}</p><label>הערה שלי ליום הזה<textarea data-flex="${esc(day.id)}" placeholder="אפשר לכתוב כאן רעיון או שינוי...">${esc(localStorage.getItem('flex_'+day.id)||'')}</textarea></label></section>`}
function prepList(){const base=['דרכון בתוקף','5 צילומי דרכון מודפסים','עותק דיגיטלי של הדרכון בטלפון ובענן','PassportCard והכרטיס הפיזי','TDAC בתוך 3 ימים לפני ההגעה','בדיקת כרטיס אשראי נוסף','בדיקת מזוודה וטרקר Google Find Hub','רישיון נהיגה בינלאומי','בדיקת eSIM / SIM','בדיקת רחפן, סוללות, כרטיס זיכרון ואישורים'];const extra=JSON.parse(localStorage.getItem('prep_extra')||'[]'),done=JSON.parse(localStorage.getItem('prep_done')||'{}');return [...base,...extra].map((t,i)=>`<label class="prep-row"><input type="checkbox" data-prep="${i}" ${done[i]?'checked':''}><span>${esc(t)}</span>${i>=base.length?`<button class="remove-prep" data-remove="${i-base.length}" type="button">מחק</button>`:''}</label>`).join('')}
function bindInline(){const close=$('#closeInline');if(close)close.onclick=()=>{$('#inlinePanel').classList.remove('show');$('#inlinePanel').innerHTML='';};$$('#inlinePanel textarea[data-flex]').forEach(t=>t.oninput=()=>localStorage.setItem('flex_'+t.dataset.flex,t.value));$$('#inlinePanel .prep-row input').forEach(x=>x.onchange=()=>{const d=JSON.parse(localStorage.getItem('prep_done')||'{}');d[x.dataset.prep]=x.checked;localStorage.setItem('prep_done',JSON.stringify(d))});$$('#inlinePanel .remove-prep').forEach(b=>b.onclick=e=>{e.preventDefault();const a=JSON.parse(localStorage.getItem('prep_extra')||'[]');a.splice(+b.dataset.remove,1);localStorage.setItem('prep_extra',JSON.stringify(a));openDay('prep')});const add=$('#addPrepBtn');if(add)add.onclick=()=>{const t=prompt('מה להוסיף להכנות?');if(!t?.trim())return;const a=JSON.parse(localStorage.getItem('prep_extra')||'[]');a.push(t.trim());localStorage.setItem('prep_extra',JSON.stringify(a));openDay('prep')}}
function openDay(id){const day=V.days.find(x=>x.id===id);if(!day)return;const panel=$('#inlinePanel');let html=`<div class="inline-head"><div>${dayIcon(day)}<div><small>${esc(day.date)}</small><h2>${esc(displayTitle(day))}</h2><p>⏱️ זמן שהות: ${esc(day.stay)}</p></div></div><button id="closeInline" class="close-red" type="button">סגור</button></div>`;if(id==='prep')html+=`<section class="info-card"><div class="section-title-row"><h3>✅ הכנות לטיול</h3><button id="addPrepBtn" class="add-btn" type="button">+ הוספה</button></div><div>${prepList()}</div></section>`;if(day.segments?.length)html+=`<section class="info-card"><h3>🚦 המסלול של היום</h3>${day.segments.map(movementCard).join('')}</section>`;html+=docsCard(day);if(day.links?.length)html+=`<section class="info-card"><h3>🔗 קישורים ויצירת קשר</h3>${linkButtons(day.links)}</section>`;html+=chabadCard(day)+flexCard(day);panel.innerHTML=html;panel.classList.add('show');bindInline();setTimeout(()=>panel.scrollIntoView({behavior:'smooth',block:'start'}),30)}
function openGeneral(){const p=$('#inlinePanel');p.innerHTML=`<div class="inline-head"><div><div class="general-icon">☰</div><div><small>כללי</small><h2>קישורים שימושיים</h2></div></div><button id="closeInline" class="close-red" type="button">סגור</button></div><section class="info-card"><h3>🧳 המזוודה שלי</h3>${linkButtons([['פתח Google Find Hub','https://www.google.com/android/find/']])}</section><section class="info-card"><h3>🚁 רחפן בתאילנד</h3>${linkButtons([['מדריך TravelGal','https://www.travelgal.co.il/post/dronethailand'],['CAAT UAS Portal','https://uasportal.caat.or.th/'],['חומר למבחן','https://uasportal.caat.or.th/basicKnow']])}</section><section class="info-card"><h3>🛂 כניסה וביטוח</h3>${linkButtons([['TDAC הרשמי','https://tdac.immigration.go.th'],['PassportCard','https://www.passportcard.co.il/']])}</section>`;p.classList.add('show');bindInline();p.scrollIntoView({behavior:'smooth',block:'start'})}

const mapStops=[
['✈️','נמל התעופה בן גוריון (Ben Gurion Airport)',32.0114,34.8867],['✈️','נמל התעופה אבו דאבי (Zayed International Airport)',24.4330,54.6511],['✈️','נמל התעופה סוברנבומי (Suvarnabhumi Airport)',13.6900,100.7501],['✈️','נמל התעופה קוסמוי (Samui Airport)',9.5478,100.0623],['🚤','נקודת Haad Rin Queen בקוסמוי',9.5584,100.0560],['🚤','רציף האד רין (Haad Rin Pier)',9.6760,100.0660],['🏨','ליטל פרדייז (Little Paradise)',9.6750,100.0675],['🎉','פול מון פארטי, האד רין נוק (Full Moon Party, Haad Rin Nok)',9.6759,100.0708],['🚤','רציף האד רין (Haad Rin Pier)',9.6760,100.0660],['🏨','סאמוי פיר ביץ׳ פרונט ריזורט (Samui Pier Beach Front Resort)',9.5584,100.0560],['✈️','נמל התעופה קוסמוי (Samui Airport)',9.5478,100.0623],['✈️','נמל התעופה צ׳יאנג מאי (Chiang Mai International Airport)',18.7668,98.9626],['🏨','ארון ראווי (Arun Rawee)',18.7900,98.9895],['🐘','אלפנט נייצ׳ר פארק (Elephant Nature Park)',19.2156,98.8597],['🚐','צ׳יאנג מאי ארקייד 2 (Chiang Mai Arcade 2)',18.8007,99.0175],['🚐','תחנת פאי (Pai Bus Station)',19.3580,98.4407],['🏨','רברי סיאם ריזורט (Reverie Siam Resort)',19.3511,98.4361],['🌳','פאי זיפליין (Pai Zipline)',19.3300,98.4300],['🚐','תחנת פאי (Pai Bus Station)',19.3580,98.4407],['🚐','צ׳יאנג מאי ארקייד 2 (Chiang Mai Arcade 2)',18.8007,99.0175],['✈️','נמל התעופה צ׳יאנג מאי (Chiang Mai International Airport)',18.7668,98.9626],['✈️','נמל התעופה סוברנבומי (Suvarnabhumi Airport)',13.6900,100.7501],['🏨','פולמן בנגקוק הוטל ג׳י (Pullman Bangkok Hotel G)',13.7257,100.5258],['✈️','נמל התעופה סוברנבומי (Suvarnabhumi Airport)',13.6900,100.7501],['✈️','נמל התעופה אבו דאבי (Zayed International Airport)',24.4330,54.6511],['✈️','נמל התעופה בן גוריון (Ben Gurion Airport)',32.0114,34.8867]
];
let mapInstance=null,mapMarkers=[];
function markerIcon(n,emoji){return L.divIcon({className:'trip-marker-wrap',html:`<div class="trip-marker"><b>${n}</b><span>${emoji}</span></div>`,iconSize:[38,38],iconAnchor:[19,34],popupAnchor:[0,-34]})}
function mapsUrl(name){return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(name)}`}
function openMap(){const wrap=$('#mapSection');wrap.classList.add('show');wrap.scrollIntoView({behavior:'smooth',block:'start'});if(mapInstance){setTimeout(()=>mapInstance.invalidateSize(),200);return}mapInstance=L.map('tripMap',{zoomControl:true}).setView([13.3,100.5],5);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(mapInstance);mapMarkers=[];const route=[];const seen={};mapStops.forEach((p,i)=>{const [emoji,name,lat,lon]=p;const key=`${lat},${lon}`;seen[key]=(seen[key]||0)+1;const k=seen[key]-1,display=[lat+(k?0.003*k:0),lon+(k?0.003*k:0)];route.push([lat,lon]);const next=mapStops[i+1];const routeLink=next?`<a href="https://www.google.com/maps/dir/?api=1&origin=${lat},${lon}&destination=${next[2]},${next[3]}" target="_blank" rel="noopener">🧭 מסלול אל נקודה ${i+2}</a>`:'';const marker=L.marker(display,{icon:markerIcon(i+1,emoji)}).addTo(mapInstance).bindPopup(`<div class="map-popup"><strong>${i+1}. ${esc(name)}</strong><a href="${mapsUrl(name)}" target="_blank" rel="noopener">📍 נווט לנקודה</a>${routeLink}</div>`);mapMarkers.push(marker)});L.polyline(route,{weight:4,opacity:.6,dashArray:'8 8'}).addTo(mapInstance);mapInstance.fitBounds(route,{padding:[30,30]});renderMapLegend();$('#mapStatus').textContent=`${mapStops.length} נקודות במסלול לפי הסדר.`}
function focusMapPoint(i){const m=mapMarkers[i];if(!m)return;mapInstance.setView(m.getLatLng(),14,{animate:true});m.openPopup();$('#tripMap').scrollIntoView({behavior:'smooth',block:'center'})}
function renderMapLegend(){$('#mapLegend').innerHTML=mapStops.map(([emoji,name],i)=>`<button type="button" data-map-index="${i}"><span>${i+1}</span><b>${emoji} ${esc(name)}</b></button>`).join('');$$('#mapLegend button').forEach(b=>b.onclick=()=>focusMapPoint(+b.dataset.mapIndex))}
$('#mapBanner').onclick=openMap;$('#mapTool').onclick=openMap;$('#closeMap').onclick=()=>$('#mapSection').classList.remove('show');$('#chabadTool').onclick=()=>window.open('https://chabadthailand.co.il/','_blank','noopener');$('#docsTool').onclick=()=>{const p=$('#inlinePanel');p.innerHTML=`<div class="inline-head"><div><div class="general-icon">🎫</div><div><small>מסמכים</small><h2>מסמכים לפי יום</h2></div></div><button id="closeInline" class="close-red" type="button">סגור</button></div>${V.days.map(d=>`<section class="info-card"><h3>${esc(d.date)} · ${esc(displayTitle(d))}</h3>${docsCard(d)}</section>`).join('')}`;p.classList.add('show');bindInline();p.scrollIntoView({behavior:'smooth',block:'start'})};
renderDays();