const V=window.TRIP_V3;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const start=new Date(V.meta.start);

function formatCountdown(ms){if(ms<=0)return 'הטיול התחיל';const d=Math.floor(ms/86400000),h=Math.floor(ms%86400000/3600000),m=Math.floor(ms%3600000/60000),s=Math.floor(ms%60000/1000);return `${String(d).padStart(2,'0')} ימים  ${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}
function tick(){const c=$('#countdownClock');if(c)c.textContent=formatCountdown(start-new Date())} tick();setInterval(tick,1000);
function currentDayId(){const n=new Date(),y=n.getFullYear(),m=String(n.getMonth()+1).padStart(2,'0'),d=String(n.getDate()).padStart(2,'0');if(n<start)return'prep';if(y===2026&&m==='09'&&+d>=25&&+d<=30)return`${d}.${m}`;if(y===2026&&m==='10'&&+d===1)return'01.10';if(y===2026&&m==='10'&&+d===2)return'02.10';if(y===2026&&m==='10'&&+d>=3&&+d<=8)return'03-08.10';if(y===2026&&m==='10'&&+d===9)return'09.10';return'prep'}
function dayIcon(day){return `<img src="${esc(day.icon)}" alt="" loading="lazy">`}
function transportType(mode=''){const m=mode.toLowerCase();if(m.includes('air')||m.includes('etihad')||m.includes('pg'))return['✈️','טיסה'];if(m.includes('ferry')||m.includes('queen')||m.includes('boat'))return['🚤','מעבורת / ספידבוט'];if(m.includes('prem pracha')||m.includes('van')||m.includes('minivan')||m.includes('מיניוואן'))return['🚐','ואן / מיניוואן'];if(m.includes('pickup')||m.includes('איסוף'))return['🚐','הסעה מאורגנת'];if(m.includes('taxi')||m.includes('grab')||m.includes('מונית'))return['🚕','מונית / Grab'];return['🚐','תחבורה']}
function cleanTitle(day){if(day.id==='prep')return'הכנות';if(day.id==='25.09')return'בנגקוק';if(day.id==='26.09')return'קוסמוי וקופנגן';if(day.id==='27.09')return'קוסמוי';if(day.id==='28.09')return'צ׳יאנג מאי';if(day.id==='29.09')return'פאי';if(day.id==='30.09')return'פאי';if(day.id==='01.10')return'בנגקוק';if(day.id==='02.10')return'בנגקוק';if(day.id==='03-08.10')return'פתוח לשינויים';if(day.id==='09.10')return'ישראל';return day.title}
function flightMeta(day){const s=(day.segments||[]).find(x=>transportType(x.mode)[1]==='טיסה');if(!s)return'';let status='שער: יתעדכן סמוך לטיסה';let link='';if((s.mode||'').toLowerCase().includes('bangkok air'))link='https://www.bangkokair.com/flight/flight-status';if((s.mode||'').toLowerCase().includes('etihad'))link='https://www.etihad.com/en/manage/flight-tracker';return `<div class="day-flight"><span>✈️ ${esc(s.mode)}</span><small>${esc(status)}</small>${link?`<a href="${link}" target="_blank" rel="noopener">בדיקת סטטוס / שער</a>`:''}</div>`}
function pierMeta(day){const s=(day.segments||[]).find(x=>transportType(x.mode)[1].includes('מעבורת'));if(!s)return'';const uncertain=s.verify?'רציף: דורש אימות':'רציף: לפי הכרטיס';return `<div class="day-flight"><span>🚤 ${esc(s.mode)}</span><small>${esc(uncertain)}</small></div>`}
function docGlyph(title=''){const t=title.toLowerCase();if(t.includes('etihad')||t.includes('bangkok air')||t.includes('טיסה'))return'✈️';if(t.includes('מעבור')||t.includes('queen')||t.includes('ferry'))return'🚤';if(t.includes('hotel')||t.includes('מלון')||t.includes('paradise')||t.includes('rawee')||t.includes('reverie')||t.includes('pullman'))return'🏨';if(t.includes('elephant')||t.includes('פיל'))return'🐘';if(t.includes('passport'))return'🛡️';return'📄'}
function renderDays(){const grid=$('#journeyGrid');const days=V.days.map(day=>`<article class="journey-card ${day.id===currentDayId()?'today-card':''}" data-day="${esc(day.id)}"><button class="day-main" type="button">${dayIcon(day)}<span>${esc(day.date)}</span><strong>${esc(cleanTitle(day))}</strong><small>⏱️ ${esc(day.stay)}</small>${flightMeta(day)}${pierMeta(day)}</button><div class="mini-docs">${(day.docs||[]).map(([t,u],i)=>`<a href="${esc(u)}" target="_blank" rel="noopener"><span class="doc-num">${i+1}</span><span class="doc-glyph">${docGlyph(t)}</span><em>${esc(t)}</em></a>`).join('')||'<span class="no-doc">אין מסמך</span>'}</div></article>`).join('');const general=`<article class="journey-card general-card"><button id="generalCard" class="day-main" type="button"><span class="small-symbol">🔗</span><span>כללי</span><strong>קישורים כלליים</strong><small>מזוודה, רחפן, כניסה, ביטוח ועוד</small></button></article>`;grid.innerHTML=days+general;$$('.journey-card[data-day] .day-main').forEach(b=>b.onclick=()=>openDay(b.closest('.journey-card').dataset.day));$('#generalCard').onclick=openGeneral}
function linkButtons(items=[]){return items.length?`<div class="action-list">${items.map(([t,u],i)=>`<a href="${esc(u)}" target="_blank" rel="noopener"><span>${i+1}</span><b>${esc(t)}</b></a>`).join('')}</div>`:''}
function movementCard(s,idx){const [ico,type]=transportType(s.mode);return `<article class="move-card"><div class="move-kicker">${ico} ${esc(type)} · קטע ${idx+1}</div><div class="move-title"><strong>מ- ${esc(s.from)}</strong><span class="to-word">אל</span><strong>${esc(s.to)}</strong></div><div class="times"><div><small>יציאה</small><b>${esc(s.depart)}</b></div><div><small>הגעה</small><b>${esc(s.arrive)}${s.duration?` <span class="duration">(${esc(s.duration)})</span>`:''}</b></div></div><div class="move-meta"><p><b>אמצעי:</b> ${esc(s.mode)}</p><p><b>🧳 מזוודה:</b> ${esc(s.luggage)}</p>${type==='טיסה'?`<p class="verify">🟠 <b>שער / רציף:</b> מתעדכן סמוך למועד. יש לבדוק בלוח הטיסות הרשמי או באפליקציית חברת התעופה.</p>`:''}${s.verify?`<p class="verify">🟠 <b>דורש אימות:</b> ${esc(s.verify)}</p>`:''}</div>${linkButtons((s.nav||[]).map(x=>[`📍 ${x[0]}`,x[1]]))}</article>`}
function docsCard(day){const docs=day.docs||[];return `<section class="info-card"><h3>🎫 מסמכים רלוונטיים</h3>${docs.length?`<div class="ordered-docs">${docs.map(([t,u],i)=>`<a href="${esc(u)}" target="_blank" rel="noopener"><span>${i+1}</span><b>${docGlyph(t)} ${esc(t)}</b></a>`).join('')}</div>`:'<p>אין כרגע מסמך ייעודי ליום הזה.</p>'}${day.folder?`<a class="folder-link" href="${esc(day.folder)}" target="_blank" rel="noopener">📂 פתח את תיקיית היום</a>`:''}</section>`}
function chabadCard(c){if(!c)return'';const arr=[['📍 נווט לבית חב״ד',c.maps],['🌐 אתר בית חב״ד',c.site]];if(c.phone)arr.push(['📞 התקשר',c.phone]);return `<section class="info-card"><h3>✡️ בית חב״ד קרוב</h3><strong>${esc(c.name)}</strong>${linkButtons(arr)}</section>`}
function flexCard(day){return `<section class="info-card flex-card"><h3>🕊️ מרווח חופשי לשינויים</h3><p>${esc(day.flex||'להשאיר זמן חופשי להחלטה במקום.')}</p><label>הערה שלי ליום הזה<textarea data-flex="${esc(day.id)}">${esc(localStorage.getItem('flex_'+day.id)||'')}</textarea></label></section>`}
function prepList(){const base=['דרכון בתוקף','5 צילומי דרכון מודפסים','עותק דיגיטלי של הדרכון בטלפון ובענן','PassportCard והכרטיס הפיזי','TDAC בתוך 3 ימים לפני ההגעה','בדיקת כרטיס אשראי נוסף','בדיקת מזוודה וטרקר Google Find Hub','רישיון נהיגה בינלאומי','בדיקת eSIM / SIM','בדיקת רחפן, סוללות, כרטיס זיכרון ואישורים'];const extra=JSON.parse(localStorage.getItem('prep_extra')||'[]'),done=JSON.parse(localStorage.getItem('prep_done')||'{}');return [...base,...extra].map((t,i)=>`<label class="prep-row"><input type="checkbox" data-prep="${i}" ${done[i]?'checked':''}><span>${esc(t)}</span>${i>=base.length?`<button class="remove-prep" data-remove="${i-base.length}" type="button">מחק</button>`:''}</label>`).join('')}
function bindInline(){const close=$('#closeInline');if(close)close.onclick=()=>{$('#inlinePanel').classList.remove('show');$('#inlinePanel').innerHTML=''};$$('#inlinePanel textarea[data-flex]').forEach(t=>t.oninput=()=>localStorage.setItem('flex_'+t.dataset.flex,t.value));$$('#inlinePanel .prep-row input').forEach(x=>x.onchange=()=>{const d=JSON.parse(localStorage.getItem('prep_done')||'{}');d[x.dataset.prep]=x.checked;localStorage.setItem('prep_done',JSON.stringify(d))});$$('#inlinePanel .remove-prep').forEach(b=>b.onclick=e=>{e.preventDefault();const a=JSON.parse(localStorage.getItem('prep_extra')||'[]');a.splice(+b.dataset.remove,1);localStorage.setItem('prep_extra',JSON.stringify(a));openDay('prep')});const add=$('#addPrepBtn');if(add)add.onclick=()=>{const t=prompt('מה להוסיף להכנות?');if(!t?.trim())return;const a=JSON.parse(localStorage.getItem('prep_extra')||'[]');a.push(t.trim());localStorage.setItem('prep_extra',JSON.stringify(a));openDay('prep')}}
function openDay(id){const day=V.days.find(x=>x.id===id);if(!day)return;const panel=$('#inlinePanel');let html=`<div class="inline-head"><div>${dayIcon(day)}<div><small>${esc(day.date)}</small><h2>${esc(cleanTitle(day))}</h2><p>⏱️ זמן שהות: ${esc(day.stay)}</p></div></div><button id="closeInline" class="close-red" type="button">סגור</button></div>`;if(id==='prep')html+=`<section class="info-card"><div class="section-title-row"><h3>✅ הכנות לטיול</h3><button id="addPrepBtn" class="add-btn" type="button">+ הוספה</button></div><div>${prepList()}</div></section>`;if(day.segments?.length)html+=`<section class="info-card"><h3>🚦 המסלול של היום</h3>${day.segments.map(movementCard).join('')}</section>`;html+=docsCard(day);if(day.links?.length)html+=`<section class="info-card"><h3>🔗 קישורים ויצירת קשר</h3>${linkButtons(day.links)}</section>`;html+=chabadCard(day)+flexCard(day);panel.innerHTML=html;panel.classList.add('show');bindInline();setTimeout(()=>panel.scrollIntoView({behavior:'smooth',block:'start'}),30)}
function openGeneral(){const p=$('#inlinePanel');p.innerHTML=`<div class="inline-head"><div><span class="small-symbol">🔗</span><div><small>כללי</small><h2>קישורים כלליים</h2></div></div><button id="closeInline" class="close-red" type="button">סגור</button></div><section class="info-card"><h3>🧳 המזוודה שלי</h3>${linkButtons([['פתח Google Find Hub','https://www.google.com/android/find/']])}</section><section class="info-card"><h3>🚁 רחפן</h3>${linkButtons([['מדריך Travel Gal','https://www.travelgal.co.il/post/dronethailand'],['CAAT UAS Portal','https://uasportal.caat.or.th/'],['חומר למבחן','https://uasportal.caat.or.th/basicKnow']])}</section><section class="info-card"><h3>🛂 כניסה וביטוח</h3>${linkButtons([['TDAC הרשמי','https://tdac.immigration.go.th'],['PassportCard','https://www.passportcard.co.il/']])}</section><section class="info-card"><h3>✡️ בתי חב״ד</h3>${linkButtons([['בתי חב״ד בתאילנד','https://chabadthailand.co.il/']])}</section>`;p.classList.add('show');bindInline();p.scrollIntoView({behavior:'smooth',block:'start'})}

const mapStops=[
['✈️','נמל התעופה בן גוריון (Ben Gurion Airport)',32.0114,34.8867],['✈️','נמל התעופה אבו דאבי (Zayed International Airport)',24.4330,54.6511],['✈️','נמל התעופה סוברנבומי (Suvarnabhumi Airport)',13.6900,100.7501],['✈️','נמל התעופה קוסמוי (Samui Airport)',9.5478,100.0623],['🚤','נקודת Haad Rin Queen בקוסמוי',9.5584,100.0560],['🚤','רציף האד רין (Haad Rin Pier)',9.6760,100.0660],['🏨','ליטל פרדייז (Little Paradise)',9.6750,100.0675],['🎉','פול מון פארטי (Full Moon Party, Haad Rin Nok)',9.6759,100.0708],['🚤','רציף האד רין (Haad Rin Pier)',9.6760,100.0660],['🏨','סאמוי פיר ביץ׳ פרונט ריזורט (Samui Pier Beach Front Resort)',9.5584,100.0560],['✈️','נמל התעופה קוסמוי (Samui Airport)',9.5478,100.0623],['✈️','נמל התעופה צ׳יאנג מאי (Chiang Mai International Airport)',18.7668,98.9626],['🏨','ארון ראווי (Arun Rawee)',18.7900,98.9895],['🐘','אלפנט נייצ׳ר פארק (Elephant Nature Park)',19.2156,98.8597],['🚐','צ׳יאנג מאי ארקייד 2 (Chiang Mai Arcade 2)',18.8007,99.0175],['🚐','תחנת פאי (Pai Bus Station)',19.3580,98.4407],['🏨','רברי סיאם ריזורט (Reverie Siam Resort)',19.3545,98.4329],['🌳','פאי זיפליין (Pai Zipline)',19.3180,98.3990],['🚐','תחנת פאי (Pai Bus Station)',19.3580,98.4407],['🚐','צ׳יאנג מאי ארקייד 2 (Chiang Mai Arcade 2)',18.8007,99.0175],['✈️','נמל התעופה צ׳יאנג מאי (Chiang Mai International Airport)',18.7668,98.9626],['✈️','נמל התעופה סוברנבומי (Suvarnabhumi Airport)',13.6900,100.7501],['🏨','פולמן בנגקוק הוטל ג׳י (Pullman Bangkok Hotel G)',13.7257,100.5255],['✈️','נמל התעופה סוברנבומי (Suvarnabhumi Airport)',13.6900,100.7501],['✈️','נמל התעופה בן גוריון (Ben Gurion Airport)',32.0114,34.8867]
];
let mapInstance=null,markers=[];
function numberedIcon(n,emoji){return L.divIcon({className:'trip-marker-wrap',html:`<div class="trip-marker"><b>${n}</b><span>${emoji}</span></div>`,iconSize:[38,38],iconAnchor:[19,34],popupAnchor:[0,-34]})}
function mapsUrl(n){const s=mapStops[n];return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(s[1])}`}
function routeUrl(n){if(n>=mapStops.length-1)return mapsUrl(n);const a=mapStops[n],b=mapStops[n+1];return `https://www.google.com/maps/dir/?api=1&origin=${a[2]},${a[3]}&destination=${b[2]},${b[3]}&travelmode=driving`}
function focusPoint(i){const s=mapStops[i],m=markers[i];if(!mapInstance||!m)return;mapInstance.flyTo([s[2],s[3]],Math.max(mapInstance.getZoom(),13),{duration:.8});m.openPopup();setTimeout(()=>document.getElementById('tripMap')?.scrollIntoView({behavior:'smooth',block:'center'}),100)}
function openMap(){const wrap=$('#mapSection');wrap.classList.add('show');wrap.scrollIntoView({behavior:'smooth',block:'start'});if(mapInstance){setTimeout(()=>mapInstance.invalidateSize(),200);return}mapInstance=L.map('tripMap',{zoomControl:true}).setView([13.3,100.5],5);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(mapInstance);markers=[];const pts=[];mapStops.forEach((s,i)=>{const ll=[s[2],s[3]];pts.push(ll);const marker=L.marker(ll,{icon:numberedIcon(i+1,s[0])}).addTo(mapInstance).bindPopup(`<div class="map-popup"><strong>${i+1}. ${esc(s[1])}</strong><a href="${mapsUrl(i)}" target="_blank" rel="noopener">📍 נווט לנקודה</a>${i<mapStops.length-1?`<a href="${routeUrl(i)}" target="_blank" rel="noopener">🧭 מסלול אל ${i+2}</a>`:''}</div>`);marker.on('click',()=>{});markers.push(marker)});L.polyline(pts,{weight:4,opacity:.6,dashArray:'8 8'}).addTo(mapInstance);mapInstance.fitBounds(pts,{padding:[35,35]});$('#mapStatus').textContent=`${mapStops.length} נקודות לפי סדר המסע.`;$('#mapLegend').innerHTML=mapStops.map((s,i)=>`<button class="map-legend-row" type="button" data-point="${i}"><span>${i+1}</span><b>${s[0]} ${esc(s[1])}</b><em>הצג במפה</em></button>`).join('');$$('.map-legend-row').forEach(b=>b.onclick=()=>focusPoint(+b.dataset.point))}
$('#mapBanner').onclick=openMap;$('#mapTool').onclick=openMap;$('#closeMap').onclick=()=>$('#mapSection').classList.remove('show');$('#docsTool').onclick=()=>{const p=$('#inlinePanel');p.innerHTML=`<div class="inline-head"><div><span class="small-symbol">🎫</span><div><small>מסמכים</small><h2>מסמכים רלוונטיים לפי יום</h2></div></div><button id="closeInline" class="close-red" type="button">סגור</button></div>${V.days.map(d=>`<section class="info-card"><h3>${esc(d.date)} · ${esc(cleanTitle(d))}</h3>${docsCard(d)}</section>`).join('')}`;p.classList.add('show');bindInline();p.scrollIntoView({behavior:'smooth',block:'start'})};$('#chabadTool').onclick=()=>window.open('https://chabadthailand.co.il/','_blank','noopener');$('#generalTool').onclick=openGeneral;
renderDays();