const V=window.TRIP_V3;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const start=new Date(V.meta.start);

function formatCountdown(ms){if(ms<=0)return 'הטיול התחיל';const d=Math.floor(ms/86400000),h=Math.floor(ms%86400000/3600000),m=Math.floor(ms%3600000/60000),s=Math.floor(ms%60000/1000);return `${String(d).padStart(2,'0')} ימים  ${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}
function tick(){const c=$('#countdownClock');if(c)c.textContent=formatCountdown(start-new Date());}
tick();setInterval(tick,1000);

function currentDayId(){const n=new Date(),y=n.getFullYear(),m=String(n.getMonth()+1).padStart(2,'0'),d=String(n.getDate()).padStart(2,'0');if(n<start)return'prep';if(y===2026&&m==='09'&&+d>=25&&+d<=30)return`${d}.${m}`;if(y===2026&&m==='10'&&+d===1)return'01.10';if(y===2026&&m==='10'&&+d===2)return'02.10';if(y===2026&&m==='10'&&+d>=3&&+d<=8)return'03-08.10';if(y===2026&&m==='10'&&+d===9)return'09.10';return'prep'}
function dayIcon(day){return `<img src="${esc(day.icon)}" alt="" loading="lazy">`}
function docGlyph(title=''){const t=title.toLowerCase();if(t.includes('etihad')||t.includes('bangkok air')||t.includes('טיסה'))return'✈️';if(t.includes('מעבור')||t.includes('queen')||t.includes('ferry'))return'🚤';if(t.includes('hotel')||t.includes('מלון')||t.includes('paradise')||t.includes('rawee')||t.includes('reverie')||t.includes('pullman'))return'🏨';if(t.includes('elephant')||t.includes('פיל'))return'🐘';if(t.includes('passport'))return'🛡️';return'📄'}
function renderDays(){const grid=$('#journeyGrid');grid.innerHTML=V.days.map(day=>`<article class="journey-card ${day.id===currentDayId()?'today-card':''}" data-day="${esc(day.id)}"><button class="day-main" type="button">${dayIcon(day)}<span>${esc(day.date)}</span><strong>${esc(day.title)}</strong><small>⏱️ ${esc(day.stay)}</small></button><div class="mini-docs">${(day.docs||[]).map(([t,u])=>`<a href="${esc(u)}" target="_blank" rel="noopener" title="${esc(t)}" aria-label="${esc(t)}">${docGlyph(t)}<em>${esc(t.replace(/^כרטיס |^שובר |^אישור /,''))}</em></a>`).join('')||'<span class="no-doc">אין מסמך</span>'}</div></article>`).join('');$$('.journey-card .day-main').forEach(b=>b.onclick=()=>openDay(b.closest('.journey-card').dataset.day));}
function linkButtons(items=[]){return items.length?`<div class="action-grid">${items.map(([t,u])=>`<a href="${esc(u)}" target="_blank" rel="noopener">${esc(t)}</a>`).join('')}</div>`:''}
function transportType(mode=''){const m=mode.toLowerCase();if(m.includes('air')||m.includes('etihad')||m.includes('pg'))return'✈️ טיסה';if(m.includes('ferry')||m.includes('queen')||m.includes('boat'))return'🚤 מעבורת / ספידבוט';if(m.includes('prem pracha')||m.includes('van')||m.includes('minivan')||m.includes('מיניוואן'))return'🚐 ואן / מיניוואן';if(m.includes('pickup')||m.includes('איסוף'))return'🚐 הסעה מאורגנת';if(m.includes('taxi')||m.includes('grab')||m.includes('מונית'))return'🚕 מונית / Grab';return'🚐 תחבורה'}
function movementCard(s,idx){return `<article class="move-card"><div class="move-kicker">קטע ${idx+1} · ${transportType(s.mode)}</div><div class="move-title"><strong>מ- ${esc(s.from)}</strong><span class="to-word">אל</span><strong>${esc(s.to)}</strong></div><div class="times"><div><small>יציאה</small><b>${esc(s.depart)}</b></div><div><small>הגעה</small><b>${esc(s.arrive)}${s.duration?` <span class="duration">(${esc(s.duration)})</span>`:''}</b></div></div><div class="move-meta"><p><b>אמצעי:</b> ${esc(s.mode)}</p><p><b>🧳 מזוודה:</b> ${esc(s.luggage)}</p>${s.verify?`<p class="verify">🟠 <b>דורש אימות מידע או נתונים:</b> ${esc(s.verify)}</p>`:''}</div>${linkButtons(s.nav||[])}</article>`}
function chabadCard(c){if(!c)return'';const arr=[['📍 נווט לבית חב״ד',c.maps],['🌐 אתר בית חב״ד',c.site]];if(c.phone)arr.push(['📞 התקשר',c.phone]);return `<section class="info-card"><h3>✡️ בית חב״ד קרוב</h3><strong>${esc(c.name)}</strong>${linkButtons(arr)}</section>`}
function docsCard(day){const docs=day.docs||[];return `<section class="info-card"><h3>🎫 מסמכים לפי סדר השימוש</h3>${docs.length?`<div class="ordered-docs">${docs.map(([t,u],i)=>`<a href="${esc(u)}" target="_blank" rel="noopener"><span>${i+1}</span><b>${docGlyph(t)} ${esc(t)}</b></a>`).join('')}</div>`:'<p>אין כרגע מסמך ייעודי ליום הזה.</p>'}${day.folder?linkButtons([['📂 פתח את תיקיית היום',day.folder]]):''}</section>`}
function flexCard(day){return `<section class="info-card flex-card"><h3>🕊️ מרווח חופשי לשינויים</h3><p>${esc(day.flex||'להשאיר זמן חופשי להחלטה במקום.')}</p><label>הערה שלי ליום הזה<textarea data-flex="${esc(day.id)}" placeholder="אפשר לכתוב כאן רעיון או שינוי...">${esc(localStorage.getItem('flex_'+day.id)||'')}</textarea></label></section>`}
function prepList(){const base=['דרכון בתוקף','5 צילומי דרכון מודפסים','עותק דיגיטלי של הדרכון בטלפון ובענן','PassportCard והכרטיס הפיזי','TDAC בתוך 3 ימים לפני ההגעה','בדיקת כרטיס אשראי נוסף','בדיקת מזוודה וטרקר Google Find Hub','רישיון נהיגה בינלאומי','בדיקת eSIM / SIM','בדיקת רחפן, סוללות, כרטיס זיכרון ואישורים'];const extra=JSON.parse(localStorage.getItem('prep_extra')||'[]'),done=JSON.parse(localStorage.getItem('prep_done')||'{}');return [...base,...extra].map((t,i)=>`<label class="prep-row"><input type="checkbox" data-prep="${i}" ${done[i]?'checked':''}><span>${esc(t)}</span>${i>=base.length?`<button class="remove-prep" data-remove="${i-base.length}" type="button">מחק</button>`:''}</label>`).join('')}
function bindInline(){const close=$('#closeInline');if(close)close.onclick=()=>{$('#inlinePanel').classList.remove('show');$('#inlinePanel').innerHTML='';};$$('#inlinePanel textarea[data-flex]').forEach(t=>t.oninput=()=>localStorage.setItem('flex_'+t.dataset.flex,t.value));$$('#inlinePanel .prep-row input').forEach(x=>x.onchange=()=>{const d=JSON.parse(localStorage.getItem('prep_done')||'{}');d[x.dataset.prep]=x.checked;localStorage.setItem('prep_done',JSON.stringify(d))});$$('#inlinePanel .remove-prep').forEach(b=>b.onclick=e=>{e.preventDefault();const a=JSON.parse(localStorage.getItem('prep_extra')||'[]');a.splice(+b.dataset.remove,1);localStorage.setItem('prep_extra',JSON.stringify(a));openDay('prep')});const add=$('#addPrepBtn');if(add)add.onclick=()=>{const t=prompt('מה להוסיף להכנות?');if(!t?.trim())return;const a=JSON.parse(localStorage.getItem('prep_extra')||'[]');a.push(t.trim());localStorage.setItem('prep_extra',JSON.stringify(a));openDay('prep')}}
function dayNavigation(day){const all=[];(day.segments||[]).forEach(s=>(s.nav||[]).forEach(x=>all.push(x)));if(!all.length)return'';return `<section class="info-card"><h3>📍 ניווטים של היום</h3>${linkButtons(all)}</section>`}
function openDay(id){const day=V.days.find(x=>x.id===id);if(!day)return;const panel=$('#inlinePanel');let html=`<div class="inline-head"><div>${dayIcon(day)}<div><small>${esc(day.date)}</small><h2>${esc(day.title)}</h2><p>⏱️ זמן שהות: ${esc(day.stay)}</p></div></div><button id="closeInline" class="close-red" type="button">סגור</button></div>`;if(id==='prep')html+=`<section class="info-card"><div class="section-title-row"><h3>✅ הכנות לטיול</h3><button id="addPrepBtn" class="add-btn" type="button">+ הוספה</button></div><div>${prepList()}</div></section>`;if(day.segments?.length)html+=`<section class="info-card"><h3>🚦 המסלול של היום</h3>${day.segments.map(movementCard).join('')}</section>`;html+=docsCard(day)+dayNavigation(day);if(day.links?.length)html+=`<section class="info-card"><h3>🔗 קישורים ויצירת קשר</h3>${linkButtons(day.links)}</section>`;html+=chabadCard(day)+flexCard(day);panel.innerHTML=html;panel.classList.add('show');bindInline();setTimeout(()=>panel.scrollIntoView({behavior:'smooth',block:'start'}),30)}

const mapStops=[
{icon:'✈️',name:'נמל התעופה בן גוריון (Ben Gurion Airport)',q:'Ben Gurion Airport Israel',ll:[32.0114,34.8867]},
{icon:'✈️',name:'נמל התעופה אבו דאבי (Zayed International Airport)',q:'Zayed International Airport Abu Dhabi',ll:[24.4330,54.6511]},
{icon:'✈️',name:'נמל התעופה סוברנבומי (Suvarnabhumi Airport)',q:'Suvarnabhumi Airport Thailand',ll:[13.6900,100.7501]},
{icon:'✈️',name:'נמל התעופה קוסמוי (Samui Airport)',q:'Samui Airport Thailand',ll:[9.5478,100.0623]},
{icon:'🚤',name:'נקודת Haad Rin Queen בקוסמוי',q:'Haad Rin Queen Ferry Koh Samui',ll:[9.5584,100.0560],note:'🟠 נקודת העלייה המדויקת דורשת אימות מול הכרטיס'},
{icon:'🚤',name:'רציף האד רין (Haad Rin Pier)',q:'Haad Rin Pier Koh Phangan',ll:[9.6760,100.0660]},
{icon:'🏨',name:'ליטל פרדייז (Little Paradise)',q:'Little Paradise Haad Rin Koh Phangan Thailand',ll:[9.6750,100.0675]},
{icon:'🎉',name:'פול מון פארטי, האד רין נוק (Full Moon Party, Haad Rin Nok)',q:'Haad Rin Nok Sunrise Beach Koh Phangan',ll:[9.6759,100.0708]},
{icon:'🚤',name:'רציף האד רין (Haad Rin Pier)',q:'Haad Rin Pier Koh Phangan',ll:[9.6760,100.0660]},
{icon:'🏨',name:'סאמוי פיר ביץ׳ פרונט ריזורט (Samui Pier Beach Front Resort)',q:'Samui Pier Beach Front Resort Thailand',ll:[9.5584,100.0560]},
{icon:'✈️',name:'נמל התעופה קוסמוי (Samui Airport)',q:'Samui Airport Thailand',ll:[9.5478,100.0623]},
{icon:'✈️',name:'נמל התעופה צ׳יאנג מאי (Chiang Mai International Airport)',q:'Chiang Mai International Airport',ll:[18.7668,98.9626]},
{icon:'🏨',name:'ארון ראווי (Arun Rawee)',q:'Arun Rawee 184 Ratchapakhinai Road Chiang Mai Thailand',ll:[18.7900,98.9895]},
{icon:'🐘',name:'אלפנט נייצ׳ר פארק (Elephant Nature Park)',q:'Elephant Nature Park Mae Taeng Chiang Mai Thailand',ll:[19.2156,98.8597]},
{icon:'🚐',name:'צ׳יאנג מאי ארקייד 2 (Chiang Mai Arcade 2)',q:'Chiang Mai Arcade Bus Terminal 2 Thailand',ll:[18.8007,99.0175]},
{icon:'🚐',name:'תחנת פאי (Pai Bus Station)',q:'Pai Bus Station Thailand',ll:[19.3580,98.4407]},
{icon:'🏨',name:'רברי סיאם ריזורט (Reverie Siam Resort)',q:'Reverie Siam Resort Pai Thailand',ll:[19.3509,98.4362]},
{icon:'🌳',name:'פאי זיפליין (Pai Zipline)',q:'Pai Zipline Thailand',ll:[19.3100,98.4240],note:'🟠 מיקום הפעילות דורש אימות בעת סגירת ההזמנה'},
{icon:'🚐',name:'תחנת פאי (Pai Bus Station)',q:'Pai Bus Station Thailand',ll:[19.3580,98.4407]},
{icon:'✈️',name:'נמל התעופה צ׳יאנג מאי (Chiang Mai International Airport)',q:'Chiang Mai International Airport',ll:[18.7668,98.9626]},
{icon:'✈️',name:'נמל התעופה סוברנבומי (Suvarnabhumi Airport)',q:'Suvarnabhumi Airport Thailand',ll:[13.6900,100.7501]},
{icon:'🏨',name:'פולמן בנגקוק הוטל ג׳י (Pullman Bangkok Hotel G)',q:'Pullman Bangkok Hotel G Thailand',ll:[13.7261,100.5250]},
{icon:'✈️',name:'נמל התעופה סוברנבומי (Suvarnabhumi Airport)',q:'Suvarnabhumi Airport Thailand',ll:[13.6900,100.7501]},
{icon:'✈️',name:'נמל התעופה אבו דאבי (Zayed International Airport)',q:'Zayed International Airport Abu Dhabi',ll:[24.4330,54.6511]},
{icon:'✈️',name:'נמל התעופה בן גוריון (Ben Gurion Airport)',q:'Ben Gurion Airport Israel',ll:[32.0114,34.8867]}
];
let mapInstance=null;
function numberedIcon(n,emoji){return L.divIcon({className:'trip-marker-wrap',html:`<div class="trip-marker"><b>${n}</b><span>${emoji}</span></div>`,iconSize:[42,42],iconAnchor:[21,38],popupAnchor:[0,-38]})}
function mapsSearch(q){return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(q)}`}
function directionsUrl(a,b){return `https://www.google.com/maps/dir/?api=1&origin=${encodeURIComponent(a.q)}&destination=${encodeURIComponent(b.q)}&travelmode=driving`}
function openMap(){const wrap=$('#mapSection');wrap.classList.add('show');wrap.scrollIntoView({behavior:'smooth',block:'start'});if(mapInstance){setTimeout(()=>mapInstance.invalidateSize(),200);return}mapInstance=L.map('tripMap',{zoomControl:true}).setView([13.3,100.5],5);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(mapInstance);const bounds=[];mapStops.forEach((p,i)=>{bounds.push(p.ll);const next=mapStops[i+1];const route=next?`<a href="${directionsUrl(p,next)}" target="_blank" rel="noopener">🧭 מסלול לנקודה ${i+2}</a>`:'';L.marker(p.ll,{icon:numberedIcon(i+1,p.icon)}).addTo(mapInstance).bindPopup(`<div class="map-popup"><strong>${i+1}. ${esc(p.name)}</strong>${p.note?`<small>${esc(p.note)}</small>`:''}<a href="${mapsSearch(p.q)}" target="_blank" rel="noopener">📍 פתח ב-Google Maps</a>${route}</div>`)});for(let i=0;i<mapStops.length-1;i++){L.polyline([mapStops[i].ll,mapStops[i+1].ll],{weight:4,opacity:.55,dashArray:'8 8'}).addTo(mapInstance)}mapInstance.fitBounds(bounds,{padding:[35,35]});$('#mapStatus').textContent=`${mapStops.length} נקודות במסלול. המספור כולל גם נקודות שחוזרים אליהן בהמשך הטיול.`;renderMapLegend()}
function renderMapLegend(){$('#mapLegend').innerHTML=mapStops.map((p,i)=>`<div><span>${i+1}</span><b>${p.icon} ${esc(p.name)}</b>${i<mapStops.length-1?`<a href="${directionsUrl(p,mapStops[i+1])}" target="_blank" rel="noopener">מסלול אל ${i+2}</a>`:''}</div>`).join('')}
$('#mapBanner').onclick=openMap;$('#mapTool').onclick=openMap;$('#closeMap').onclick=()=>$('#mapSection').classList.remove('show');$('#trackerTool').onclick=()=>window.open('https://www.google.com/android/find/','_blank','noopener');$('#chabadTool').onclick=()=>window.open('https://chabadthailand.co.il/','_blank','noopener');$('#docsTool').onclick=()=>{const p=$('#inlinePanel');p.innerHTML=`<div class="inline-head"><div><div class="big-ico">🎫</div><div><small>מסמכים לפי יום</small><h2>כל המסמכים במקום אחד</h2></div></div><button id="closeInline" class="close-red" type="button">סגור</button></div>${V.days.map(d=>`<section class="info-card"><h3>${esc(d.date)} · ${esc(d.title)}</h3>${docsCard(d)}</section>`).join('')}`;p.classList.add('show');bindInline();p.scrollIntoView({behavior:'smooth',block:'start'})};
renderDays();