const V=window.TRIP_V3;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const start=new Date(V.meta.start);

function tick(){const ms=start-new Date(),d=$('#countdownDays'),h=$('#countdownHours');if(ms<=0){if(d)d.textContent='הטיול התחיל';if(h)h.textContent='';return;}const days=Math.floor(ms/86400000),hours=Math.floor(ms%86400000/3600000),mins=Math.floor(ms%3600000/60000),secs=Math.floor(ms%60000/1000);if(d)d.textContent=`${days} ימים`;if(h)h.textContent=`${String(hours).padStart(2,'0')}:${String(mins).padStart(2,'0')}:${String(secs).padStart(2,'0')}`;}tick();setInterval(tick,1000);
function cleanTitle(day){if(day.id==='prep')return'הכנות';if(day.id==='25.09')return'בנגקוק';if(day.id==='26.09')return'קוסמוי וקופנגן';if(day.id==='27.09')return'קוסמוי';if(day.id==='28.09')return'צ׳יאנג מאי';if(day.id==='29.09'||day.id==='30.09')return'פאי';if(day.id==='01.10'||day.id==='02.10')return'בנגקוק';if(day.id==='03-08.10')return'פתוח לשינויים';if(day.id==='09.10')return'ישראל';return day.title;}
function dayIcon(day){return `<img src="${esc(day.icon)}" alt="" loading="lazy">`;}
function nextDay(day){const i=V.days.findIndex(x=>x.id===day.id);return i>=0&&i<V.days.length-1?V.days[i+1]:null;}
function renderDays(){const g=$('#journeyGrid');g.innerHTML=V.days.map(day=>`<button class="day-tile" data-day="${esc(day.id)}" type="button"><span class="tiny-icon">${dayIcon(day)}</span><span class="tile-date">${esc(day.date)}</span><strong>${esc(cleanTitle(day))}</strong></button>`).join('')+`<button id="generalLinksCard" class="day-tile general-tile" type="button"><span class="tiny-icon">☰</span><span class="tile-date">כללי</span><strong>קישורים שימושיים</strong></button>`;$$('.day-tile[data-day]').forEach(b=>b.onclick=()=>openDay(b.dataset.day));$('#generalLinksCard').onclick=openGeneral;}
function linkButtons(items=[]){return items.length?`<div class="action-stack">${items.map(([t,u])=>`<a href="${esc(u)}" target="_blank" rel="noopener">${esc(t)}</a>`).join('')}</div>`:'';}
function transportType(mode=''){const m=mode.toLowerCase();if(m.includes('air')||m.includes('etihad')||m.includes('pg'))return'✈️ טיסה';if(m.includes('ferry')||m.includes('queen')||m.includes('boat'))return'🚤 מעבורת / ספידבוט';if(m.includes('prem pracha')||m.includes('van')||m.includes('minivan')||m.includes('מיניוואן'))return'🚐 ואן / מיניוואן';if(m.includes('איסוף')||m.includes('elephant'))return'🚐 הסעה מאורגנת';if(m.includes('taxi')||m.includes('grab')||m.includes('מונית'))return'🚕 מונית / Grab';return'🚐 תחבורה';}
function isFlight(s){const m=(s?.mode||'').toLowerCase();return m.includes('air')||m.includes('etihad')||/pg\d+/i.test(s?.mode||'');}
function flightBoard(s){if(!isFlight(s))return'';const f=s.from||'';let u='',l='';if(f.includes('תל אביב')){u='https://www.iaa.gov.il/en/';l='לוח הטיסות נתב״ג';}else if(f.includes('אבו דאבי')){u='https://www.zayedinternationalairport.ae/en/flights-and-check-in/flight-status/departures';l='לוח הטיסות אבו דאבי';}else if(f.includes('בנגקוק')){u='https://suvarnabhumi.airportthai.co.th/flight?type=departure';l='לוח הטיסות סוברנבומי';}else if(f.includes('צ׳יאנג מאי')||f.includes("צ'יאנג מאי")){u='https://chiangmai.airportthai.co.th/flight?type=departure';l='לוח הטיסות צ׳יאנג מאי';}else if(f.includes('קוסמוי')){u='https://www.bangkokair.com/';l='Bangkok Airways - בדיקת טיסה';}return u?`<a href="${u}" target="_blank" rel="noopener">🛫 ${l}</a>`:'';}
function movementCard(s,idx){const board=flightBoard(s);return `<article class="move-card"><div class="move-kicker">${idx+1}. ${transportType(s.mode)}</div><div class="move-title"><strong>מ- ${esc(s.from)}</strong><span>אל</span><strong>${esc(s.to)}</strong></div><div class="times"><div><small>יציאה</small><b>${esc(s.depart)}</b></div><div><small>הגעה</small><b>${esc(s.arrive)}</b>${s.duration?`<em>${esc(s.duration)}</em>`:''}</div></div><p><b>אמצעי:</b> ${esc(s.mode)}</p><p><b>🧳 מזוודה:</b> ${esc(s.luggage)}</p>${s.verify?`<p class="verify">🟠 ${esc(s.verify)}</p>`:''}<div class="action-stack">${board}${(s.nav||[]).map(([t,u])=>`<a href="${esc(u)}" target="_blank" rel="noopener">📍 ${esc(t)}</a>`).join('')}</div></article>`;}
function docPurpose(title=''){const t=title.toLowerCase();if(t.includes('etihad')||t.includes('bangkok air'))return'כרטיס טיסה';if(t.includes('מעבור')||t.includes('queen')||t.includes('ferry')||t.includes('speedboat'))return'כרטיס למעבורת';if(t.includes('prem pracha')||t.includes('van')||t.includes('מיניוואן'))return'כרטיס לוואן';if(t.includes('elephant')||t.includes('zipline')||t.includes('פיל')||t.includes('אומגה'))return'כרטיס / אישור לאטרקציה';if(t.includes('hotel')||t.includes('מלון')||t.includes('paradise')||t.includes('rawee')||t.includes('reverie')||t.includes('pullman'))return'שובר מלון';if(t.includes('passport'))return'מסמך ביטוח';return'מסמך רלוונטי';}
function docsCard(day){const docs=day.docs||[];return `<section class="info-card"><h3>🎫 מסמכים רלוונטיים</h3>${docs.length?`<div class="ordered-docs">${docs.map(([t,u],i)=>`<a href="${esc(u)}" target="_blank" rel="noopener"><span>${i+1}</span><div><b>${esc(docPurpose(t))}</b><small>${esc(t)}</small></div></a>`).join('')}</div>`:'<p>אין כרגע מסמך ייעודי ליום הזה.</p>'}${day.folder?`<a class="folder-link" href="${esc(day.folder)}" target="_blank" rel="noopener">📂 תיקיית היום</a>`:''}</section>`;}
function chabadCard(c){if(!c)return'';const a=[['📍 נווט לבית חב״ד',c.maps],['🌐 אתר בית חב״ד',c.site]];if(c.phone)a.push(['📞 התקשר',c.phone]);return `<section class="info-card"><h3>✡️ בית חב״ד קרוב</h3><strong>${esc(c.name)}</strong>${linkButtons(a)}</section>`;}
function flexCard(day){return `<section class="info-card"><h3>🕊️ זמן חופשי לשינויים</h3><p>${esc(day.flex||'להשאיר זמן חופשי להחלטה במקום.')}</p></section>`;}
function prepList(){const base=['דרכון בתוקף','5 צילומי דרכון מודפסים','עותק דיגיטלי של הדרכון בטלפון ובענן','PassportCard והכרטיס הפיזי','TDAC בתוך 3 ימים לפני ההגעה','בדיקת כרטיס אשראי נוסף','בדיקת מזוודה וטרקר Google Find Hub','רישיון נהיגה בינלאומי','בדיקת eSIM / SIM','בדיקת רחפן, סוללות, כרטיס זיכרון ואישורים'];const extra=JSON.parse(localStorage.getItem('prep_extra')||'[]'),done=JSON.parse(localStorage.getItem('prep_done')||'{}');return [...base,...extra].map((t,i)=>`<label class="prep-row"><input type="checkbox" data-prep="${i}" ${done[i]?'checked':''}><span>${esc(t)}</span>${i>=base.length?`<button class="remove-prep" data-remove="${i-base.length}" type="button">מחק</button>`:''}</label>`).join('');}
function bindInline(){const c=$('#closeInline');if(c)c.onclick=()=>{$('#inlinePanel').classList.remove('show');$('#inlinePanel').innerHTML='';};$$('#inlinePanel .prep-row input').forEach(x=>x.onchange=()=>{const d=JSON.parse(localStorage.getItem('prep_done')||'{}');d[x.dataset.prep]=x.checked;localStorage.setItem('prep_done',JSON.stringify(d));});$$('#inlinePanel .remove-prep').forEach(b=>b.onclick=e=>{e.preventDefault();const a=JSON.parse(localStorage.getItem('prep_extra')||'[]');a.splice(+b.dataset.remove,1);localStorage.setItem('prep_extra',JSON.stringify(a));openDay('prep');});const add=$('#addPrepBtn');if(add)add.onclick=()=>{const t=prompt('מה להוסיף להכנות?');if(!t?.trim())return;const a=JSON.parse(localStorage.getItem('prep_extra')||'[]');a.push(t.trim());localStorage.setItem('prep_extra',JSON.stringify(a));openDay('prep');};}
function openDay(id){const day=V.days.find(x=>x.id===id);if(!day)return;const n=nextDay(day),p=$('#inlinePanel');let html=`<div class="inline-head"><div><small>${esc(day.date)}</small><h2>${esc(cleanTitle(day))}</h2><p>⏱️ ${esc(day.stay)}${n?` · היעד הבא: ${esc(cleanTitle(n))}`:''}</p></div><button id="closeInline" class="close-red" type="button">סגור</button></div>`;if(id==='prep')html+=`<section class="info-card"><div class="section-title-row"><h3>✅ הכנות לטיול</h3><button id="addPrepBtn" class="add-btn" type="button">+ הוספה</button></div>${prepList()}</section>`;if(day.segments?.length)html+=`<section class="info-card"><h3>🚦 המסלול של היום</h3>${day.segments.map(movementCard).join('')}</section>`;html+=docsCard(day);if(day.links?.length)html+=`<section class="info-card"><h3>🔗 קישורים ויצירת קשר</h3>${linkButtons(day.links)}</section>`;html+=chabadCard(day)+flexCard(day);p.innerHTML=html;p.classList.add('show');bindInline();setTimeout(()=>p.scrollIntoView({behavior:'smooth',block:'start'}),30);}
function openGeneral(){const p=$('#inlinePanel');p.innerHTML=`<div class="inline-head"><div><small>כללי</small><h2>קישורים שימושיים</h2></div><button id="closeInline" class="close-red" type="button">סגור</button></div><section class="info-card">${linkButtons([['🧳 Google Find Hub','https://www.google.com/android/find/'],['🚁 CAAT UAS Portal','https://uasportal.caat.or.th/'],['🇮🇱 מדריך רחפן Travel Gal','https://www.travelgal.co.il/post/dronethailand'],['🛂 TDAC הרשמי','https://tdac.immigration.go.th'],['✡️ בתי חב״ד בתאילנד','https://chabadthailand.co.il/']])}</section>`;p.classList.add('show');bindInline();p.scrollIntoView({behavior:'smooth',block:'start'});}

const mapStops=[['✈️','נמל התעופה בן גוריון (Ben Gurion Airport)',32.0114,34.8867],['✈️','נמל התעופה אבו דאבי (Zayed International Airport)',24.4330,54.6511],['✈️','נמל התעופה סוברנבומי (Suvarnabhumi Airport)',13.6900,100.7501],['✈️','נמל התעופה קוסמוי (Samui Airport)',9.5478,100.0623],['🚤','נקודת Haad Rin Queen בקוסמוי',9.5584,100.0560],['🚤','רציף האד רין (Haad Rin Pier)',9.6760,100.0660],['🏨','ליטל פרדייז (Little Paradise)',9.6750,100.0675],['🎉','פול מון פארטי, האד רין נוק (Full Moon Party, Haad Rin Nok)',9.6759,100.0708],['🚤','רציף האד רין (Haad Rin Pier)',9.6760,100.0660],['🏨','סאמוי פיר ביץ׳ פרונט ריזורט (Samui Pier Beach Front Resort)',9.5584,100.0560],['✈️','נמל התעופה קוסמוי (Samui Airport)',9.5478,100.0623],['✈️','נמל התעופה צ׳יאנג מאי (Chiang Mai International Airport)',18.7668,98.9626],['🏨','ארון ראווי (Arun Rawee)',18.7900,98.9895],['🐘','אלפנט נייצ׳ר פארק (Elephant Nature Park)',19.2156,98.8597],['🚐','צ׳יאנג מאי ארקייד 2 (Chiang Mai Arcade 2)',18.8007,99.0175],['🚐','תחנת פאי (Pai Bus Station)',19.3580,98.4407],['🏨','רברי סיאם ריזורט (Reverie Siam Resort)',19.3511,98.4361],['🌳','פאי זיפליין (Pai Zipline)',19.3300,98.4300],['🚐','תחנת פאי (Pai Bus Station)',19.3580,98.4407],['🚐','צ׳יאנג מאי ארקייד 2 (Chiang Mai Arcade 2)',18.8007,99.0175],['✈️','נמל התעופה צ׳יאנג מאי (Chiang Mai International Airport)',18.7668,98.9626],['✈️','נמל התעופה סוברנבומי (Suvarnabhumi Airport)',13.6900,100.7501],['🏨','פולמן בנגקוק הוטל ג׳י (Pullman Bangkok Hotel G)',13.7257,100.5258],['✈️','נמל התעופה סוברנבומי (Suvarnabhumi Airport)',13.6900,100.7501],['✈️','נמל התעופה אבו דאבי (Zayed International Airport)',24.4330,54.6511],['✈️','נמל התעופה בן גוריון (Ben Gurion Airport)',32.0114,34.8867]];
let mapInstance=null,mapMarkers=[];
function markerIcon(n,emoji){return L.divIcon({className:'trip-marker-wrap',html:`<div class="trip-marker"><b>${n}</b><span>${emoji}</span></div>`,iconSize:[38,38],iconAnchor:[19,34],popupAnchor:[0,-34]});}
function mapsUrl(name){return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(name)}`;}
function openMap(){const wrap=$('#mapSection');wrap.classList.add('show');wrap.scrollIntoView({behavior:'smooth',block:'start'});if(mapInstance){setTimeout(()=>mapInstance.invalidateSize(),200);return;}mapInstance=L.map('tripMap',{zoomControl:true}).setView([13.3,100.5],5);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(mapInstance);mapMarkers=[];const route=[],seen={};mapStops.forEach((p,i)=>{const [emoji,name,lat,lon]=p,key=`${lat},${lon}`;seen[key]=(seen[key]||0)+1;const k=seen[key]-1,display=[lat+(k?0.003*k:0),lon+(k?0.003*k:0)];route.push([lat,lon]);const next=mapStops[i+1];const routeLink=next?`<a href="https://www.google.com/maps/dir/?api=1&origin=${lat},${lon}&destination=${next[2]},${next[3]}" target="_blank" rel="noopener">🧭 מסלול אל נקודה ${i+2}</a>`:'';const marker=L.marker(display,{icon:markerIcon(i+1,emoji)}).addTo(mapInstance).bindPopup(`<div class="map-popup"><strong>${i+1}. ${esc(name)}</strong><a href="${mapsUrl(name)}" target="_blank" rel="noopener">📍 נווט לנקודה</a>${routeLink}</div>`);mapMarkers.push(marker);});L.polyline(route,{weight:4,opacity:.6,dashArray:'8 8'}).addTo(mapInstance);mapInstance.fitBounds(route,{padding:[30,30]});renderMapLegend();$('#mapStatus').textContent=`${mapStops.length} נקודות במסלול לפי הסדר.`;}
function focusMapPoint(i){const m=mapMarkers[i];if(!m)return;mapInstance.setView(m.getLatLng(),14,{animate:true});m.openPopup();$('#tripMap').scrollIntoView({behavior:'smooth',block:'center'});}
function renderMapLegend(){$('#mapLegend').innerHTML=mapStops.map(([emoji,name],i)=>`<button type="button" class="map-legend-row" data-map-index="${i}"><span>${i+1}</span><b>${emoji} ${esc(name)}</b><em>הצג במפה</em></button>`).join('');$$('#mapLegend button').forEach(b=>b.onclick=()=>focusMapPoint(+b.dataset.mapIndex));}
$('#mapBanner').onclick=openMap;$('#mapTool').onclick=openMap;$('#closeMap').onclick=()=>$('#mapSection').classList.remove('show');$('#chabadTool').onclick=()=>window.open('https://chabadthailand.co.il/','_blank','noopener');$('#docsTool').onclick=()=>{const p=$('#inlinePanel');p.innerHTML=`<div class="inline-head"><div><small>מסמכים</small><h2>מסמכים לפי יום</h2></div><button id="closeInline" class="close-red" type="button">סגור</button></div>${V.days.map(d=>docsCard(d)).join('')}`;p.classList.add('show');bindInline();p.scrollIntoView({behavior:'smooth',block:'start'});};
renderDays();