const D=window.TRIP_DATA,S=D.meta.routeStatusLegend;
const q=id=>document.getElementById(id);
const e=s=>String(s??'').replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const shortStatus=k=>({confirmed:'🟢 סגור',planned:'🟡 מתוכנן',decision:'🟠 דורש אימות מידע או נתונים',missing:'🔴 חסר',open:'⚪ פתוח'}[k]||S[k]||k);
const start=new Date('2026-09-25T15:05:00+03:00'),now=new Date(),diff=start-now,days=Math.max(0,Math.floor(diff/86400000)),hours=Math.max(0,Math.floor((diff%86400000)/3600000)),mins=Math.max(0,Math.floor((diff%3600000)/60000));
if(q('countdownChip')) q('countdownChip').textContent=diff>0?`${days} ימים · ${hours} שעות · ${mins} דקות`:'✈️ הטיול התחיל';
if(q('countdownMini')) q('countdownMini').textContent=diff>0?`עוד ${days} ימים`:'הטיול התחיל';
const flow=x=>{const steps=x.steps||[];if(!steps.length)return'';return `<div class="travel-flow"><strong>🧭 מה עושים עכשיו?</strong>${steps.map((s,i)=>`<div class="flow-step"><span>${i+1}</span><p>${e(s)}</p></div>`).join('')}${x.verify?`<div class="verify-box">🟠 <strong>דורש אימות מידע או נתונים:</strong> ${e(x.verify)}</div>`:`<div class="verified-box">🟢 מידע תפעולי מאומת לפי ההזמנה הקיימת.</div>`}</div>`};
const card=x=>`<article class="route-card"><div class="top"><div class="date">${e(x.date)}</div><div class="status">${e(shortStatus(x.transportStatus))}</div></div><div class="route-grid"><div><div class="place">${e(x.from)}</div><div class="time">${e(x.departure)}</div></div><div class="arrow">&gt;</div><div><div class="place">${e(x.to)}</div><div class="time">${e(x.arrival)}</div></div></div><div class="meta"><div><strong>🚐 תחבורה</strong>${e(x.transport)}</div><div><strong>✨ מה עושים</strong>${e(x.activity)}</div>${x.hotel?`<div><strong>🏨 מלון</strong>${e(x.hotel)}</div>`:''}<div><strong>🧳 איפה המזוודה</strong>${e(x.luggage)}</div>${x.whyOpen?`<div><strong>ℹ️ למה לא סגור</strong>${e(x.whyOpen)}</div>`:''}<div><strong>📌 סטטוס פעילות</strong>${e(shortStatus(x.activityStatus))}</div></div>${flow(x)}${x.maps?`<div class="actions"><a target="_blank" rel="noopener" href="${e(x.maps)}">📍 נווט אותי</a></div>`:''}</article>`;
function renderRoute(items,title='המסלול שלי'){q('routeList').innerHTML=items.map(card).join('');if(q('routeTitle'))q('routeTitle').textContent=title;if(q('routeStats'))q('routeStats').innerHTML='';}
renderRoute(D.itinerary);
const state=JSON.parse(localStorage.getItem('th_public_checklist')||'{}');
if(q('checklistList')){q('checklistList').innerHTML=D.checklist.map((c,i)=>`<label class="row-card check-row"><input type="checkbox" data-i="${i}" ${state[i]?'checked':''}><span>${e(c.text)}</span></label>`).join('');document.querySelectorAll('#checklistList input').forEach(x=>x.onchange=()=>{const s=JSON.parse(localStorage.getItem('th_public_checklist')||'{}');s[x.dataset.i]=x.checked;localStorage.setItem('th_public_checklist',JSON.stringify(s));});}
const setNavActive=id=>{document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.remove('active','nav-active'));if(id==='home')q('homeBtn')?.classList.add('nav-active');else document.querySelector(`.bottom-nav button[data-tab="${id}"]`)?.classList.add('active')};
const switchTab=id=>{document.querySelectorAll('.tab-panel').forEach(x=>x.classList.remove('active'));q(id)?.classList.add('active');setNavActive(id);setTimeout(()=>q(id)?.scrollIntoView({behavior:'smooth',block:'start'}),20)};
document.querySelectorAll('.bottom-nav button[data-tab]').forEach(b=>b.onclick=()=>{if(b.dataset.tab==='route')renderRoute(D.itinerary);switchTab(b.dataset.tab)});
q('homeBtn')?.addEventListener('click',()=>{renderRoute(D.itinerary);document.querySelectorAll('.tab-panel').forEach(x=>x.classList.remove('active'));q('route')?.classList.add('active');setNavActive('home');window.scrollTo({top:0,behavior:'smooth'})});
q('trackerBtn')?.addEventListener('click',()=>window.open('https://www.google.com/android/find/','_blank','noopener'));
q('checkBtn')?.addEventListener('click',()=>switchTab('checklist'));
document.querySelectorAll('.day-btn').forEach(b=>b.addEventListener('click',()=>{const d=b.dataset.date,items=D.itinerary.filter(x=>x.date===d);renderRoute(items,d==='25.09'?'יום הטיסה':`יום ${d}`);switchTab('route')}));
q('updatesBtn')?.addEventListener('click',()=>switchTab('checklist'));
q('nowBanner')?.addEventListener('click',()=>{if(diff>0){switchTab('checklist');return;}renderRoute(D.itinerary);switchTab('route')});
if(diff>0){q('nowBannerTitle').textContent='הכנות לטיול';q('nowBannerText').textContent=`עוד ${days} ימים לטיסה · לחץ לפתיחת ההכנות`;q('nextTitle').textContent='הכנות לטיול';q('nextText').textContent='דרכון, מסמכים, ביטוח, מזוודה ו-TDAC';}else{q('nowBannerTitle').textContent='המסע התחיל';q('nowBannerText').textContent='לחץ כדי לראות מה עושים עכשיו';q('nextTitle').textContent='מה עושים עכשיו?';q('nextText').textContent='פתח את היום הנוכחי במסלול';}