window.TRIP_V3={
meta:{start:'2026-09-25T15:05:00+03:00',return:'2026-10-09T11:10:00+03:00',cancelled:['22203']},
mapPoints:[
['נמל התעופה בן גוריון (Ben Gurion Airport)','https://www.google.com/maps/search/?api=1&query=Ben+Gurion+Airport'],
['נמל התעופה סוברנבומי (Suvarnabhumi Airport)','https://www.google.com/maps/search/?api=1&query=Suvarnabhumi+Airport'],
['נמל התעופה קוסמוי (Samui Airport)','https://www.google.com/maps/search/?api=1&query=Samui+Airport'],
['ליטל פרדייז (Little Paradise)','https://www.google.com/maps/search/?api=1&query=Little+Paradise+Haad+Rin+Koh+Phangan'],
['סאמוי פיר ביץ׳ פרונט ריזורט (Samui Pier Beach Front Resort)','https://www.google.com/maps/search/?api=1&query=Samui+Pier+Beach+Front+Resort'],
['ארון ראווי (Arun Rawee)','https://www.google.com/maps/search/?api=1&query=Arun+Rawee+Chiang+Mai'],
['אלפנט נייצ׳ר פארק (Elephant Nature Park)','https://www.google.com/maps/search/?api=1&query=Elephant+Nature+Park+Chiang+Mai'],
['צ׳יאנג מאי ארקייד 2 (Chiang Mai Arcade 2)','https://www.google.com/maps/search/?api=1&query=Chiang+Mai+Arcade+Bus+Terminal+2'],
['רברי סיאם ריזורט (Reverie Siam Resort)','https://www.google.com/maps/search/?api=1&query=Reverie+Siam+Resort+Pai'],
['פאי זיפליין (Pai Zipline)','https://www.google.com/maps/search/?api=1&query=Pai+Zipline+Thailand'],
['פולמן בנגקוק הוטל ג׳י (Pullman Bangkok Hotel G)','https://www.google.com/maps/search/?api=1&query=Pullman+Bangkok+Hotel+G']
],
days:[
{id:'prep',date:'לפני הטיסה',title:'הכנות',icon:'https://cdn.jsdelivr.net/gh/twitter/twemoji@latest/assets/svg/1f9f3.svg',stay:'עד 25.9 בשעה 15:05',folder:'https://drive.google.com/drive/folders/1kwPBGJPVqVVyhkHdBbTb_zgpaDnRLfat',docs:[['פוליסת PassportCard','https://drive.google.com/file/d/1QGmyATF6DTEGTZnq0zKFotXvH8FzSKFb/view']],links:[['TDAC הרשמי','https://tdac.immigration.go.th'],['CAAT לרחפן','https://uasportal.caat.or.th/']],flex:'להשאיר את ערב 24.9 רגוע, בלי סידורים שאפשר לסיים קודם.'},
{id:'25.09',date:'25.9',title:'יום הטיסה',icon:'https://cdn.jsdelivr.net/gh/twitter/twemoji@latest/assets/svg/2708.svg',stay:'יום תנועה, ללא לינה',folder:'https://drive.google.com/drive/folders/1PdiZ0M__0zQqvsJ6-_lRMKmFK6pW7gh5',segments:[{from:'תל אביב (Tel Aviv)',to:'אבו דאבי (Abu Dhabi)',depart:'15:05',arrive:'19:15',duration:'כ-3:10 שעות טיסה',mode:'Etihad',luggage:'נמסרת בנתב״ג; לוודא תג עד בנגקוק',nav:[['נווט לנתב״ג','https://www.google.com/maps/search/?api=1&query=Ben+Gurion+Airport']]},{from:'אבו דאבי (Abu Dhabi)',to:'בנגקוק (Bangkok)',depart:'21:10',arrive:'06:45 למחרת',duration:'כ-6:35 שעות טיסה',mode:'Etihad',luggage:'אמורה להמשיך לפי תג הכבודה',verify:'שער וטרמינל נבדקים סמוך לטיסה'}],docs:[['כרטיס Etihad','https://drive.google.com/file/d/1FUGVjP8WtyDQ6JYbdtC9zHKKtSt3uv17/view']],links:[['Etihad','https://www.etihad.com/']],flex:'לא לתכנן דבר נוסף. המטרה היחידה היא להגיע רגוע לבנגקוק.'},
{id:'26.09',date:'26.9',title:'קוסמוי וקופנגן',icon:'https://cdn.jsdelivr.net/gh/twitter/twemoji@latest/assets/svg/1f389.svg',stay:'קופנגן: כ-24:35 שעות עד המעבורת למחרת',folder:'https://drive.google.com/drive/folders/1Nbe0j6ZmOGpmsRca8HXWGwGOY9zlf6W_',segments:[{from:'בנגקוק (Bangkok)',to:'קוסמוי (Koh Samui)',depart:'10:10',arrive:'11:40',duration:'כ-1:30 שעות טיסה',mode:'Bangkok Airways PG127',luggage:'איסוף בקוסמוי',nav:[['נווט לשדה סוברנבומי','https://www.google.com/maps/search/?api=1&query=Suvarnabhumi+Airport'],['נווט לשדה קוסמוי','https://www.google.com/maps/search/?api=1&query=Samui+Airport']]},{from:'קוסמוי (Koh Samui)',to:'האד רין, קופנגן (Haad Rin, Koh Phangan)',depart:'15:00',arrive:'15:25',duration:'כ-25 דקות הפלגה',mode:'Haad Rin Queen Speedboat',luggage:'איתך במעבורת',verify:'נקודת היציאה המדויקת בקוסמוי דורשת אימות',nav:[['נווט לחיפוש רציף Haad Rin Queen','https://www.google.com/maps/search/?api=1&query=Haad+Rin+Queen+Ferry+Koh+Samui'],['נווט לליטל פרדייז','https://www.google.com/maps/search/?api=1&query=Little+Paradise+Haad+Rin+Koh+Phangan']] }],docs:[['כרטיס Bangkok Airways','https://drive.google.com/file/d/1CbN0MrM0m0DeMyolQi925dz_hRqOOlMA/view'],['כרטיס המעבורת','https://drive.google.com/file/d/1aPFq-0Z2lKYYH75zGLLAExzUGSz6vDNe/view'],['שובר Little Paradise','https://drive.google.com/file/d/14IL7LFr5k_ZLTb2JHTiDj6G3XuFYh4Km/view']],links:[['Full Moon Party הרשמי','https://www.fullmoonpartythailand.com/'],['Haad Rin Queen','https://www.haadrinqueen.com/Home'],['Bangkok Airways','https://www.bangkokair.com/']],chabad:{name:'בית חב״ד קופנגן (Chabad Koh Phangan)',site:'https://chabadthailand.co.il/houses/koh-phangan/',maps:'https://www.google.com/maps/search/?api=1&query=Chabad+Koh+Phangan',phone:'tel:+66927610635'},flex:'אחרי הצ׳ק-אין לא לקבוע עוד אטרקציה. לשמור כוחות למסיבת הפול מון.'},
{id:'27.09',date:'27.9',title:'התאוששות וקוסמוי',icon:'https://cdn.jsdelivr.net/gh/twitter/twemoji@latest/assets/svg/26f4.svg',stay:'קוסמוי: כ-16:05 שעות עד הטיסה למחרת',folder:'https://drive.google.com/drive/folders/16zckGJaYmfDbhzk2sxaO-UmN85cyP-1f',segments:[{from:'קופנגן (Koh Phangan)',to:'קוסמוי (Koh Samui)',depart:'16:00',arrive:'16:50',duration:'כ-50 דקות הפלגה',mode:'Haadrin Queen Ferry',luggage:'איתך במעבורת',nav:[['נווט לרציף האד רין','https://www.google.com/maps/search/?api=1&query=Haad+Rin+Queen+Pier+Koh+Phangan'],['נווט למלון בקוסמוי','https://www.google.com/maps/search/?api=1&query=Samui+Pier+Beach+Front+Resort']]}],docs:[['כרטיס המעבורת','https://drive.google.com/file/d/1lqfDfPCa3NZxZhgkNQt6-uYw07NfdS9I/view'],['שובר המלון בקוסמוי','https://drive.google.com/file/d/1jxavc3PsSUK8qxdkbboIa_zsc95WL8yY/view']],links:[['Haad Rin Queen','https://www.haadrinqueen.com/Home'],['טלפון Haad Rin Queen','tel:+6677375113']],chabad:{name:'בית חב״ד קוסמוי (Chabad Koh Samui)',site:'https://chabadthailand.co.il/houses/koh-samui/',maps:'https://www.google.com/maps/search/?api=1&query=Chabad+Koh+Samui',phone:'tel:+66800095052'},flex:'יום התאוששות. לא לקבוע כלום עד אחר הצהריים, ואחרי המלון רק אוכל, מסאז׳ או הליכה קלה.'},
{id:'28.09',date:'28.9',title:'צ׳יאנג מאי',icon:'https://cdn.jsdelivr.net/gh/twitter/twemoji@latest/assets/svg/1f3ef.svg',stay:'צ׳יאנג מאי: כ-29:50 שעות עד היציאה לפאי',folder:'https://drive.google.com/drive/folders/1gyiMl3uiA5FTWiJi3ZoIGNv4zCJfokIh',segments:[{from:'קוסמוי (Koh Samui)',to:'צ׳יאנג מאי (Chiang Mai)',depart:'08:55',arrive:'10:40',duration:'כ-1:45 שעות טיסה',mode:'Bangkok Airways PG241',luggage:'איסוף בצ׳יאנג מאי',nav:[['נווט לשדה קוסמוי','https://www.google.com/maps/search/?api=1&query=Samui+Airport'],['נווט לארון ראווי','https://www.google.com/maps/search/?api=1&query=Arun+Rawee+Chiang+Mai']]}],docs:[['כרטיס Bangkok Airways','https://drive.google.com/file/d/1o221H467DDSda8HgyLo7zt-xxgsuzXK_/view'],['שובר Arun Rawee','https://drive.google.com/file/d/1NK-ALRroQwrgZE4s601wGhRICCuydLZs/view']],chabad:{name:'בית חב״ד צ׳יאנג מאי (Chabad Chiang Mai)',site:'https://chabadthailand.co.il/houses/chiang-mai/',maps:'https://www.google.com/maps/search/?api=1&query=Chabad+Chiang+Mai',phone:'tel:+66861111770'},flex:'אחרי הצ׳ק-אין להשאיר את היום פתוח: עיר עתיקה, קפה, מסאז׳ ושוק לפי החשק.'},
{id:'29.09',date:'29.9',title:'פילים ופאי',icon:'https://cdn.jsdelivr.net/gh/twitter/twemoji@latest/assets/svg/1f418.svg',stay:'פאי: כ-36:10 שעות עד המיניוואן המועדף ב-1.10',folder:'https://drive.google.com/drive/folders/18rshWrWZAwyixSa8JrXp9VZg2LQahb9i',segments:[{from:'ארון ראווי, צ׳יאנג מאי (Arun Rawee, Chiang Mai)',to:'אלפנט נייצ׳ר פארק (Elephant Nature Park)',depart:'07:30-08:00',arrive:'כ-09:30',duration:'כ-1:30 שעות נסיעה משוערות',mode:'איסוף של Elephant Nature Park',luggage:'נשארת במלון',nav:[['נווט ל-Elephant Nature Park','https://www.google.com/maps/search/?api=1&query=Elephant+Nature+Park+Chiang+Mai']]},{from:'צ׳יאנג מאי ארקייד 2 (Chiang Mai Arcade 2)',to:'פאי (Pai)',depart:'16:30',arrive:'20:50',duration:'כ-4:20 שעות נסיעה',mode:'Prem Pracha',luggage:'איתך במיניוואן',nav:[['נווט ל-Chiang Mai Arcade 2','https://www.google.com/maps/search/?api=1&query=Chiang+Mai+Arcade+Bus+Terminal+2'],['נווט ל-Reverie Siam Resort','https://www.google.com/maps/search/?api=1&query=Reverie+Siam+Resort+Pai']]}],docs:[['אישור Elephant Nature Park','https://docs.google.com/document/d/17e6Xv7_dvwUs2FtPIA3jj2lC9f8aWWS5NLa77SfUwDg/edit'],['כרטיס Prem Pracha','https://drive.google.com/file/d/1_IqzOrun-lf02MhYvVaXIGblkbPSENUI/view'],['שובר Reverie Siam','https://drive.google.com/file/d/1GOko2F5gNObDvRxphx5t-km5O-9-Hfrr/view']],links:[['Elephant Nature Park','https://elephantnaturepark.org/visit-volunteer/half-day-morning-visit-to-elephant-nature-park/'],['טלפון Elephant Nature Park','tel:+6653272855'],['אימייל Elephant Nature Park','mailto:info@elephantnaturepark.org']],chabad:{name:'בית חב״ד פאי (Chabad Pai)',site:'https://chabadthailand.co.il/houses/pai/',maps:'https://www.google.com/maps/search/?api=1&query=Chabad+Pai+Thailand',phone:'tel:+66657195466'},flex:'אחרי ההגעה לפאי לא לתכנן דבר. מקלחת, אוכל ומנוחה.'},
{id:'30.09',date:'30.9',title:'פאי וזיפליין',icon:'https://cdn.jsdelivr.net/gh/twitter/twemoji@latest/assets/svg/1f9d7.svg',stay:'יום מלא בפאי; לינה שנייה באותו מלון',folder:'https://drive.google.com/drive/folders/1jmrr5NERgpCCG6IEURZNiDkzpGQbsx-6',segments:[{from:'רברי סיאם ריזורט, פאי (Reverie Siam Resort, Pai)',to:'פאי זיפליין (Pai Zipline)',depart:'סביב 10:00',arrive:'טרם נסגר',duration:'זמן הנסיעה טרם אומת',mode:'תחבורה טרם נסגרה',luggage:'נשארת במלון',verify:'צריך לאמת איסוף מהמלון, שעת התחלה ודרך חזרה',nav:[['נווט ל-Pai Zipline','https://www.google.com/maps/search/?api=1&query=Pai+Zipline+Thailand']]}],links:[['Pai Zipline Package A','https://paizipline.com/product/package-a/'],['טלפון Pai Zipline','tel:+66967894449'],['אימייל Pai Zipline','mailto:pai.zip.line99@gmail.com']],chabad:{name:'בית חב״ד פאי (Chabad Pai)',site:'https://chabadthailand.co.il/houses/pai/',maps:'https://www.google.com/maps/search/?api=1&query=Chabad+Pai+Thailand',phone:'tel:+66657195466'},flex:'אחרי האומגה כל היום פתוח. הצעה: קפה, שוק הלילה, מסאז׳ או פשוט בריכה במלון.'},
{id:'01.10',date:'1.10',title:'פאי לבנגקוק',icon:'https://cdn.jsdelivr.net/gh/twitter/twemoji@latest/assets/svg/1f3d9.svg',stay:'בנגקוק: 2 לילות סגורים עד 3.10; ההמשך פתוח',folder:'https://drive.google.com/drive/folders/128KOLW3MO-X6ovEOq8_yapiPzkCUHeKK',segments:[{from:'פאי (Pai)',to:'צ׳יאנג מאי (Chiang Mai)',depart:'09:00 מועדף',arrive:'12:55 משוער',duration:'כ-3:55 שעות נסיעה',mode:'Prem Pracha, טרם הוזמן',luggage:'איתך',verify:'המיניוואן עדיין לא הוזמן'},{from:'צ׳יאנג מאי (Chiang Mai)',to:'בנגקוק (Bangkok)',depart:'20:00',arrive:'21:25',duration:'כ-1:25 שעות טיסה',mode:'Bangkok Airways PG220',luggage:'נמסרת ב-CNX ונאספת ב-BKK',nav:[['נווט לשדה צ׳יאנג מאי','https://www.google.com/maps/search/?api=1&query=Chiang+Mai+International+Airport'],['נווט ל-Pullman Bangkok Hotel G','https://www.google.com/maps/search/?api=1&query=Pullman+Bangkok+Hotel+G']]}],docs:[['כרטיס Bangkok Airways','https://drive.google.com/file/d/1JihNVU2SmhMChpAFUo5lR4fXt7V2uyZ_/view'],['שובר Pullman Bangkok Hotel G','https://drive.google.com/file/d/1-akqfhsk3hwsj8MAy3pRPt2zhOYTj0fY/view']],chabad:{name:'בית חב״ד בנגקוק (Chabad Bangkok)',site:'https://chabadthailand.co.il/houses/bangkok/',maps:'https://www.google.com/maps/search/?api=1&query=Chabad+House+Bangkok+18+Phra+Athit+Road',phone:'tel:+6626292770'},flex:'אחרי הצ׳ק-אין אין תכנון חובה. רק לאכול ולצאת אם נשאר כוח.'},
{id:'02.10',date:'2.10',title:'בנגקוק חופשי',icon:'https://cdn.jsdelivr.net/gh/twitter/twemoji@latest/assets/svg/1f6b6.svg',stay:'לילה שני ב-Pullman Bangkok Hotel G',folder:'https://drive.google.com/drive/folders/1uZJjDCUPbKCWWYAHKPFmXnjbwxJ67klz',chabad:{name:'בית חב״ד בנגקוק (Chabad Bangkok)',site:'https://chabadthailand.co.il/houses/bangkok/',maps:'https://www.google.com/maps/search/?api=1&query=Chabad+House+Bangkok+18+Phra+Athit+Road',phone:'tel:+6626292770'},flex:'יום חופשי אמיתי. לבחור תוך כדי: שוק, קניון, מסאז׳, אוכל, סילום או פשוט לשוטט.'},
{id:'03-08.10',date:'3-8.10',title:'פתוח לשינויים',icon:'https://cdn.jsdelivr.net/gh/twitter/twemoji@latest/assets/svg/1f5d3.svg',stay:'6 ימים פתוחים בכוונה',folder:'https://drive.google.com/drive/folders/11SGdn4s-c5IRW1S51fZ3FquIafzAehib',chabad:{name:'בתי חב״ד בתאילנד (Chabad Thailand)',site:'https://chabadthailand.co.il/',maps:'https://www.google.com/maps/search/?api=1&query=Chabad+Thailand'},flex:'זהו מרחב הגמישות העיקרי. לא לסגור עכשיו רק כדי למלא ימים. אפשר להישאר בבנגקוק או להוסיף יעד רק אם באמת מתחשק.'},
{id:'09.10',date:'9.10',title:'חזרה לישראל',icon:'https://cdn.jsdelivr.net/gh/twitter/twemoji@latest/assets/svg/2708.svg',stay:'חזרה הביתה ב-11:10',folder:'https://drive.google.com/drive/folders/1JWLTiiztI-HweXJnZ1pMjF008naDO-oi',segments:[{from:'בנגקוק (Bangkok)',to:'אבו דאבי (Abu Dhabi)',depart:'03:15',arrive:'06:45',duration:'כ-6:30 שעות טיסה',mode:'Etihad',luggage:'נמסרת בבנגקוק; לוודא תג עד תל אביב'},{from:'אבו דאבי (Abu Dhabi)',to:'תל אביב (Tel Aviv)',depart:'08:45',arrive:'11:10',duration:'כ-3:25 שעות טיסה',mode:'Etihad',luggage:'איסוף בנתב״ג',nav:[['נווט לנתב״ג','https://www.google.com/maps/search/?api=1&query=Ben+Gurion+Airport']]}],docs:[['כרטיס Etihad','https://drive.google.com/file/d/11IJHK64yk6xT4V3lpXW52B60y3ndUIP9/view']],links:[['Etihad','https://www.etihad.com/']],flex:'לא לתכנן כלום ליום החזרה.'}
]
};